### ISSUE TITLE
Fix hyperlinks in the Android tutorials section of wiki

### ISSUE THREAD

**Issue by sturmen** [uber/RIBs#108]
Attached is a patch file with the proper URLs. Had to change to `.txt` from `.diff` due to GitHub's restrictions.
[wikipatch.txt](https://github.com/uber/RIBs/files/1446176/wikipatch.txt)

**Comment by artman** [comment]
Thank you @sturmen. I'd rather like to take #109, which renames the tutorial folders to match the wiki documentation.

**Comment by leobrujah** [comment]
Just to point out that there's a broken link in the "RIBs plugin jar" under the [Tooling Section](https://github.com/uber/RIBs/tree/master/android/tooling/rib-intellij-plugin)

**Comment by artman** [comment]
This has been resolved.
