### ISSUE TITLE
tutorial 1 : provided sample code at https://raw.githubusercontent.com/uber/ribs/assets/tutorial_assets/ios/tutorial1-create-a-rib/source/source1.swift  has constraint errors, due to usage of snapkit

### ISSUE THREAD

**Issue by yaboisandeep** [uber/RIBs#115]
<img width="318" alt="screen shot 2017-11-07 at 3 03 07 pm" src="https://user-images.githubusercontent.com/18097615/32486642-39234a98-c3cd-11e7-9980-040109a5a1af.png">

**Comment by yaboisandeep** [comment]
importing snapkit fixes the issue

**Comment by kovpas** [comment]
@artman there are a few solutions to this:
- write in [the tutorial](https://github.com/uber/RIBs/wiki/iOS-Tutorial-1) something like "make sure to import SnapKit so the project compiles"
- Provide the entire file in [the assets](https://github.com/uber/RIBs/blob/assets/tutorial_assets/ios/tutorial1-create-a-rib/source/source1.swift).

Which one is better you think?

**Comment by artman** [comment]
I think it makes more sense to add this to the tutorial wiki, as the file has already been created by the tooling.

**Comment by kovpas** [comment]
Done.
