### ISSUE TITLE
Android - Remove synthetic accessors

### ISSUE THREAD

**Issue by bangarharshit** [uber/RIBs#116]
There are around 44 synthetic accessors (15 in main code).  Remove them to reduce dex count.

**Comment by AttwellBrian** [comment]
I'm curious: did you just manually read through the code to find these? Or did you run a tool. 

I have a pretty good idea where they are. But interested in how you did this generally.

**Comment by bangarharshit** [comment]
Through IntelliJ inspections. It is in beta and not enabled by default so you need to enable it from preferences (J2ME). 

https://medium.com/thoughts-overflow/effects-of-javas-synthetic-accessor-methods-in-android-bb67b3bac22e

**Comment by hzsweers** [comment]
Only if doing so doesn't create weird API holes

**Comment by AttwellBrian** [comment]
Of course. Synthetic accessors can be valuable.

And when profiling RIB classes I haven't seen much time spent inside the RIB base classes.

**Comment by artman** [comment]
Closing as stale.
