### ISSUE TITLE
slack for RIBs community

### ISSUE THREAD

**Issue by oronbz** [uber/RIBs#122]
Hi guys,
One of the most powerful things within the RxSwift community is communication (no pun intended) with slack.

How are you maintainers and other contributors feeling about creating a slack server for RIBs?

I personally think this could speed up the advancement and maturity of this project, along with people who will be there to clear things up and make RIBs integration an ease.

**Comment by artman** [comment]
That makes perfect sense. I'll look into this once I get some free time.

**Comment by igordeoliveirasa** [comment]
I agree!

**Comment by namhvcntt** [comment]
need a slack channel.

**Comment by kronik** [comment]
let's start a discussion: uber-ribs.slack.com

**Comment by namhvcntt** [comment]
invite me: namhv.cntt@gmail.com

**Comment by kronik** [comment]
Uber guys are welcome to become owners / administrators of this workspace

**Comment by dmarjanovic** [comment]
invitation please :) dragan.marjanovic at gmail.com 👍

**Comment by tailec** [comment]
krawiecky@gmail.com please

**Comment by edrew08** [comment]
If this is the official slack channel, it should be added to the readme.

**Comment by dangthaison91** [comment]
Should we create a website to automatically invite people? Anybody can help?

**Comment by kronik** [comment]
@dangthaison91 I don't really know how to do this. Any help is appreciated :) PS: added you.

**Comment by kronik** [comment]
I'll try to setup this thing: https://github.com/outsideris/slack-invite-automation

**Comment by kronik** [comment]
Done! please visit: https://uber-ribs-invite-automation.herokuapp.com to receive an invite :D

**Comment by dangthaison91** [comment]
Wow, nice work @kronik? I think you should make a PR to add Slack link :D

**Comment by dangthaison91** [comment]
Thanks and nice work @kronik . A pull request  to add Slack link will be amazing.

**Comment by kronik** [comment]
@dangthaison91 I doubt they will accept it :)

**Comment by kronik** [comment]
@artman what do you think?

**Comment by artman** [comment]
This is pretty great, thanks for doing this! Unfortunately we can't really officially point to web-services or channels that are not under our control. I'll circle back with the team to discuss whether we could set up a channel of our own.

**Comment by artman** [comment]
Closing out stale issues.
