### ISSUE TITLE
[iOS] Sanity check tutorial #1 and tutorial #2

### ISSUE THREAD

**Issue by artman** [uber/RIBs#123]
I just updated tutorial #1 and tutorial #2 in terms of language, more helpful explanations and missing code snippets and ran through them to make sure that they work. Could someone do a second sanity check and just run through the tutorials to make sure that they make sense? If you find any problems or spelling mistakes, feel free to update the wiki directly.

**Comment by igordeoliveirasa** [comment]
i think its less confusing when class properties are declared on top of them instead of along of class as they are currently.
