### ISSUE TITLE
[iOS] Tutorial #4 wiki entry

### ISSUE THREAD

**Issue by artman** [uber/RIBs#125]
The entry is still missing.

**Comment by kovpas** [comment]
@artman the tutorial [is done](https://github.com/uber/RIBs/wiki/iOS-Tutorial-4). Would appreciate if you have a look.

**Comment by artman** [comment]
Thanks @kovpas! I'll go through it once I'm done with tutorial 3. Will keep this open until then.

**Comment by artman** [comment]
This is now updated.
