### ISSUE TITLE
Add differences between RIBs and MVC to the README

### ISSUE THREAD

**Issue by artman** [uber/RIBs#127]
This make the README more approachable, we should explain the differences between RIBs and MVC in the README.

**Comment by hzsweers** [comment]
That might be a slippery slope. MVP is a common pattern on Android (and we do have Presenters), VIPER is probably what RIBs are most similar to, etc

**Comment by gergelyorosz** [comment]
I see the value in doing this. I will do a first pass and share it with the two of you for feedback.

**Comment by gergelyorosz** [comment]
First draft [here](https://docs.google.com/a/uber.com/document/d/1eVfYasmYdFZTVZgOV10Y5H5nxOxBn4o-AaEtjwOpvGw/edit?usp=sharing) (internal only). Feedback welcome!

**Comment by gergelyorosz** [comment]
Addressed with #150.
