### ISSUE TITLE
FrameLayout should be LinearLayout in tutorial 1

### ISSUE THREAD

**Issue by eduardb** [uber/RIBs#130]
In tutorial 1 in the wiki, the paragraph
 ```In order for this view to work, you'll need to update the LoggedOutView to inherit from FrameLayout.```
 should read 
```In order for this view to work, you'll need to update the LoggedOutView to inherit from LinearLayout.```. 

See file in tutorial 2: https://github.com/uber/RIBs/blob/e532c90d17b9302d271cb3663c11eb06cbd5ec83/android/tutorials/tutorial2/src/main/java/com/uber/rib/root/logged_out/LoggedOutView.java#L19

**Comment by gergelyorosz** [comment]
Thanks for pointing it out! Fixed by @AttwellBrian .
