### ISSUE TITLE
Options for Template Generating

### ISSUE THREAD

**Issue by igordeoliveirasa** [uber/RIBs#132]
As I'm working on a library and I'll have to 'export' multiple classes and protocols, I'd love if template generating toll could have an option for generating protocols as 'public'  and classes as 'open' automatically.

**Comment by sbarow** [comment]
Hi @igordeoliveirasa as mentioned in [131](https://github.com/uber/RIBs/issues/131) all that is needed to expose RIBs to other modules is to make the `Buildable`,  `Dependency`, `Routing`, and `Listener` protocols as well as the RIBs `Builder` as public. This isn't something we need to cover in templates as the majority of your RIBs should just be scoped to the module they are in.
