### ISSUE TITLE
Xcode Template weirdness: XInteractable protocol is in XRouter and vice versa

### ISSUE THREAD

**Issue by oronbz** [uber/RIBs#136]
Hi, I've noticed a really weird oddity with the Xcode RIB templates and I wonder if it's by design and why.

When I create a RIB called `X` I've noticed that the `XInteractable` protocol is declared on `XRouter` file and the `XRouting` protocol is declared on `XInteractor` file.

I'll be happy to fix it in a pull request and wonder if there's any reasoning behind it? Because I find it confusing.

**Comment by artman** [comment]
The XRouter declares the XInteractable protocol, since that's what it wants from its Interactor. Similarly, the XRouting is defined in XInteractor, since that's what it wants from its router. We chose this arrangement so that the call-site would contain the interface that you can call out to.

**Comment by oronbz** [comment]
Got it! Thanks @artman
