### ISSUE TITLE
Broken link - Completed Tutorial 4

### ISSUE THREAD

**Issue by igordeoliveirasa** [uber/RIBs#137]
Link: https://github.com/uber/RIBs/tree/master/ios/tutorials/tutorial4-completed is broken.

**Comment by sbarow** [comment]
Should be fixed now - just merged [129](https://github.com/uber/RIBs/pull/129)

**Comment by igordeoliveirasa** [comment]
Thanks. 
sbarow, could you add an example about cancelling current game? I'm facing with "memory leak" problems trying to "come back" to the "root". I guess this example would help us even more about detaching.

**Comment by sbarow** [comment]
Sure, I'll have a look. cc @kovpas

**Comment by igordeoliveirasa** [comment]
If you could give me a tip right now, how would you do to cancel game from OffGameViewController? (minimal steps that will help me a lot)
Thanks.

**Comment by sbarow** [comment]
You want to navigate from OffGame to LoggedOut?

**Comment by igordeoliveirasa** [comment]
Yes.

**Comment by igordeoliveirasa** [comment]
Like close game / logout operation.

**Comment by igordeoliveirasa** [comment]
Im making any mistake on this kind of flow.

**Comment by sbarow** [comment]
Closing as this is fixed - can discuss the next issue in [#140](https://github.com/uber/RIBs/issues/140)

**Comment by igordeoliveirasa** [comment]
Thanks. I'll open another Question Issue instead of continuing to #140, since it's another kind of doubt, ok?

**Comment by sbarow** [comment]
I believe it should be related to the same question, no need for another one.
