### ISSUE TITLE
RIBs tips about not checking: 'Owns corresponding view'

### ISSUE THREAD

**Issue by igordeoliveirasa** [uber/RIBs#139]
There are an example that teaches us how to create LoggedIn RIBs which its router manipulates parent's view controller. That's nice.. However, what if I had to manipulate parents presenter from LoggedIn Interactor?

For better understanding, imagine that this interactor have some business rules that may throw some exceptions.. I'd like to order presentable to display those errors.

Thanks.

**Comment by igordeoliveirasa** [comment]
For better understanding, imagine that this interactor have some business rules that may throw some exceptions.. I'd like to order presentable to display those errors.

**Comment by sbarow** [comment]
Answered in #156
