### ISSUE TITLE
Detaching Child

### ISSUE THREAD

**Issue by igordeoliveirasa** [uber/RIBs#140]
In tutorial we learn the below code so as to detach current child:

```swift
private func detachCurrentChild() {
        if let currentChild = currentChild as? ViewableRouting {
            detachChild(currentChild)
            viewController.dismiss(viewController: currentChild.viewControllable)
        }
    }
```

A question: May I also use that method so as to detach children from RIBs which doesn't own View? If no, how could detach them? I suppose, the right method should be like that, Am I right? Follows:

```swift
private func detachCurrentChild() {
        if currentChild != nil {
            detachChild(currentChild!)
        }
        
        if let currentChild = currentChild as? ViewableRouting {
            viewController.dismiss(viewController: currentChild.viewControllable)
        }
    }
```

**Comment by igordeoliveirasa** [comment]
@sbarow could you help me? It's not so clear to me.

**Comment by kovpas** [comment]
Yes, that looks correct.

Depending on your needs you could have a separate method for every child router that is attached. That way you'd know if the child you're about to detach is a `ViewableRouting` or not:

```swift
private func detachSettingsFlow() { // assuming settingsFlow is a vieweless RIB
    guard let settingsFlowRouter = self.settingsFlowRouter else {
        return
    }
        
    detachChild(settingsRouter)
}

private func detachMainMenu() {  // assuming mainMenu is a RIB with a view
    guard let mainMenu = self.mainMenu else {
        return
    }
        
    detachChild(mainMenu)
    viewController.dismiss(viewController: mainMenu.viewControllable)
}
```

**Comment by igordeoliveirasa** [comment]
@kovpas but, lets suppose we have 10 kinds of detaching methods like in your example. And I have 10 kinds of routeTo<SomeState>() method... I'll have to make many conditions to know what kind of "detach" method to call.. That's driving me a bit crazy.. Your clarification will be much helpful.

**Comment by kovpas** [comment]
Why would you make any conditions? If router A attaches routers B and C, and at some point wants to detach one of them, it'll just invoke a method `detachC` or `detachB`, and will be done. Could you please clarify your question?

**Comment by artman** [comment]
Closing as stale.
