### ISSUE TITLE
Android tutorial 1 issues

### ISSUE THREAD

**Issue by oronbz** [uber/RIBs#143]
Hi I would love to correct those issues by myself but as you know one does not simply make a PR for Wiki.

* Step 5 - `In order for this view to work, you'll need to update the LoggedOutView to inherit from FrameLayout.` this should be changed to `LinearLayout` to compliment your suggested layout. (https://github.com/uber/RIBs/issues/130)

* Step 5 - You forgot to mention adding the following line:
```return (LoggedOutView) inflater.inflate(R.layout.logged_out_rib, parentViewGroup, false);``` 
instead of 
```return null;``` 
inside:
```protected LoggedOutView inflateView(LayoutInflater inflater, ViewGroup parentViewGroup)```.

**Comment by AttwellBrian** [comment]
Updated.

**Comment by AttwellBrian** [comment]
Thanks for letting us know.
