### ISSUE TITLE
More real-life examples

### ISSUE THREAD

**Issue by kronik** [uber/RIBs#145]
I'm very excited to see a different approach to a flexible mobile architectures. And I'd ask for more examples including side menu, tabbar, list of elements, details of elements, network interactions, etc.

**Comment by ManWithBear** [comment]
Check out this issue: #131

**Comment by dev4jam** [comment]
I've created a sample app to show major of use cases: https://github.com/dev4jam/ToDo

**Comment by Fi5t** [comment]
What about android real-life examples?

**Comment by tyvsmith** [comment]
PRs would gladly be welcome (for external or Uber employees), but I don't see the Ribs maintainers prioritizing adding additional sample apps at the moment. There are a number of existing Android ones now, including using Compose and Coroutines APIs, if there's a specific one being looked for.
