### ISSUE TITLE
Dependency & Component Extensions Tool

### ISSUE THREAD

**Issue by igordeoliveirasa** [uber/RIBs#147]
If framework had 'RootComponent+LoggedOff.swift' kind of files generator would be really helpful!
I can notice that because I've been converting a huge project to use RIBs framework (I do believe on this framework.). It's a bit annoying to create those files manually. And it's so easy to get confused.

Thanks.

**Comment by sbarow** [comment]
There is a template for component extensions in our templates [ios/tooling](https://github.com/uber/RIBs/tree/master/ios/tooling)

**Comment by igordeoliveirasa** [comment]
My XCode is showing only RIBs and Unit Test. Not showing 'Component/Dependency' type.

<img width="722" alt="screen shot 2017-11-16 at 14 04 03" src="https://user-images.githubusercontent.com/2123428/32901507-19f63674-cad7-11e7-99bf-5b1443aacd95.png">

**Comment by sbarow** [comment]
@igordeoliveirasa pull the latest & run `./ios/install-xcode-template.sh`

**Comment by igordeoliveirasa** [comment]
@sbarow Thanks! Now it appears. 👍

**Comment by igordeoliveirasa** [comment]
@sbarow Thanks! Now it appears. 👍
