### ISSUE TITLE
Routing didLoad method not called

### ISSUE THREAD

**Issue by igordeoliveirasa** [uber/RIBs#148]
Scenario:
RIB A1 routes to RIB B
RIB A2 also routes to the same RIB B

Where: RIB A1 and A2 own view but RIB B does not own view, the didLoad of RIB B Routing is not called.

**Comment by sbarow** [comment]
Did you attach the child RIB i.e RIB B to A1/2? Info can be found in [iOS-Tutorial-2](https://github.com/uber/RIBs/wiki/iOS-Tutorial-2)

**Comment by igordeoliveirasa** [comment]
@sbarow Oh yeah! It was missing! Thank you so much!

By the way, I had a confusion with components extension of RIB A called by 2. I had to do something like that:

RIB A1
```swift
extension ...Component: ...Dependency {
    var ...ViewController: ...ViewControllable {
        return self.dependency.myViewController
    }
}
```

RIB A2
```swift
extension ...Component: ...Dependency {
    var ...ViewController: ...ViewControllable {
        return self.myViewController
    }
}
```

One of them I had to call from self.dependency and another from self.

Is that right?

**Comment by sbarow** [comment]
This would depend on how you have structured your dependencies and components.

In A1 case it means you have defined that as a dependency and in A2 case you haven't but have the variable as part of your component.

**Comment by igordeoliveirasa** [comment]
By the way, it would be nice if we could have an example of a RIB being routed from 2 or more other ribs.

**Comment by igordeoliveirasa** [comment]
@sbarow Ok, in the beginning it's a bit complex to understand components and those inversion protocols. But its awesome! Let's keep on practicing... 👍
