### ISSUE TITLE
Carthage Error

### ISSUE THREAD

**Issue by ronzohan** [uber/RIBs#149]
I can't seem to integrate RIBs using Carthage. Upon running `carthage update --platform iOS`, carthage will fail with this error message in the log file 

```
diff: /Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.
```

Any idea on what's causing this?

**Comment by sbarow** [comment]
We are working on a solution [#138](https://github.com/uber/RIBs/pull/138) for now you can use the `carthage` branch.

Just update your `Cartfile` to point to:
```
github "uber/RIBs" "carthage"
```

**Comment by ronzohan** [comment]
Okay thanks but I think there is still an error on that branch because RIBs can't actually find the carthage folder since its in the root folder. 

I made it worked by changing `Framework Search Paths` into `$(PROJECT_DIR)/../Carthage/Build/iOS`

**Comment by sbarow** [comment]
Thanks for the info @ronzohan is that error when you are checking out RIBs and trying to build the actual RIB project or when you are adding RIBs to a project through Carthage?

**Comment by ronzohan** [comment]
The error occurs on adding RIBs to a project through Carthage. Running `carthage update` would fail building the dependency.

**Comment by sbarow** [comment]
@ronzohan updated the path, you should be able to use this from master now. Please let me know if you have any issues.

**Comment by Kievkao** [comment]
Still get the same problem

**Comment by sbarow** [comment]
I'll create a new release with updated version number, should fix the issue.
