### ISSUE TITLE
Question about 'currentChild' router's variable of tutorial

### ISSUE THREAD

**Issue by igordeoliveirasa** [uber/RIBs#158]
I'd like to know if instead of declaring and keep setting 'currentChild' whenever I attach a new state, I could suppose that if I retrieve 'self.children.last' is the same reference and if it's better then manual 'currentChild' handling...

**Comment by AttwellBrian** [comment]
> `self.children.last`

Do you mean `self.currentChild` or `self.children.last`? You wouldn't want to store multiple last children in memory if you have detached some of them. That is a memory leak.

>  if it's better then manual 'currentChild' handling...

Sounds like your children are mutually exclusive and you want a convenient way to manage their mutual exclusivity?

You could definately write a utility that makes this easier. The `RouterNavigator` class in this repo is one such example (granted it is more complicated than you need). If you write such a utility be careful to avoid building the children more often then necessary.

**Comment by igordeoliveirasa** [comment]
@AttwellBrian all RIB's routers offer us a 'children' property by default. When we call attach(..) RIB's framework add it to 'children'.

**Comment by artman** [comment]
Closing out stale issues.
