### ISSUE TITLE
Global services

### ISSUE THREAD

**Issue by kronik** [uber/RIBs#161]
If I create a remote API service instance and local configuration management service instance in AppComponent what will be a correct way of passing them into LoggedInInteractor and further?

Currently, I've added them to RIB's dependency and pass them to the interactor when a builder builds the RIB through an interactor's constructor. And if I have more dependencies in interactor, it's constructor parameters will blow up.  Is there any way to access component or dependency in interactor? Will it be a better option to pass entire component to interactor on create?

**Comment by sbarow** [comment]
The way you have mentioned is the recommended approach as thats essential what the `Builder` is there for, to pass in the dependencies for its `router` & `interactor`. For unit testing it also makes it super clear what the `Interactor` would need in this case. Yes you could pass in the `dependency` (the component conforms to the dependency so you can pass in either) but I am not sure this is the best approach.

**Comment by kronik** [comment]
Got it. thanks!
