### ISSUE TITLE
Unbalanced calls to begin/end appearance transitions

### ISSUE THREAD

**Issue by ronzohan** [uber/RIBs#165]
The warning `"The unbalanced calls to begin/end appearance transitions"` seems to occur on my RootViewController RIB when the RootRouter tries to present another controller. The warning occurs when a view controller tries to present the another view controller even though the presenting view controller has not finished displaying. Any idea on preventing this warning to occur?

**Comment by neakor** [comment]
That warning is usually because the parent view controller has not been fully presented yet, before the child view controller is presented. RIBs doesn't deal with any UIKit specific logic. Perhaps you can show some more code of how the root view controller is attached to window and how you present the second view controller? It's difficult to debug without seeing any code.

**Comment by ronzohan** [comment]
```
@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {

    var window: UIWindow?

    private var launchRouter: LaunchRouting?

    func application(_: UIApplication,
                     didFinishLaunchingWithOptions _: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
        let window = UIWindow(frame: UIScreen.main.bounds)
        self.window = window

        let launchRouter = RootBuilder(dependency: AppComponent()).build()
        self.launchRouter = launchRouter

        launchRouter.launchFromWindow(window)
    
        return true
    }
}


final class RootRouter: LaunchRouter<RootInteractable, RootViewControllable>, RootRouting {
    // MARK: - Private
    private let listingBuilder: ListingBuildable

    init(interactor: RootInteractable,
         viewController: RootViewControllable,
         listingBuilder: ListingBuildable) {
        self.listingBuilder = listingBuilder
        super.init(interactor: interactor, viewController: viewController)
        interactor.router = self
    }

    override func didLoad() {
        super.didLoad()

        routeToListing(withSubreddit: "all")
    }

    func routeToListing(withSubreddit subreddit: String) {
        let listing = listingBuilder.build(withListener: interactor, subreddit: subreddit)
        attachChild(listing)
        
        viewController.present(viewController: listing.viewControllable)
    }
}
```

Above is my sample root router and how it is presented

AFAIK the warning also occurs in the sample tutorials.

**Comment by neakor** [comment]
The `listing` VC is being presented in the same runloop cycle as the root VC is assigned to the window, while making the window visible. This will indeed cause a warning.

I think we should consider why the listing VC is separated from root to begin with? If we want listing to be attached to root at all times, as it's indicated by using the `didLoad` method for attachment, then there really isn't a lifecycle difference between root and listing. Perhaps we can collapse listing RIB entirely into root. If we think there are significant dependency differences between the two scopes, then perhaps a separate listing scope is warranted. In that case, we may want to only collapse the VC hierarchy, by combining the listing VC with the root VC.

**Comment by ronzohan** [comment]
Making the listing as the root does makes sense as the root VC does nothing except for presenting the listing vc.

This makes sense to me now. Thank you and cheers! 🍻🍻

**Comment by neakor** [comment]
Happy to help!
