### ISSUE TITLE
Proposal: Make a demo of the google architecture examples for Android

### ISSUE THREAD

**Issue by hzsweers** [uber/RIBs#166]
See https://github.com/googlesamples/android-architecture

We'd talked about this awhile back as a really good example for demoing RIBs in a context that's both familiar and comparable to other common architectures. This repo is sort of the go-to standard for comparing/demoing different architectures

**Comment by aitorvs** [comment]
Hi there,
I was just implementing the [RIBs sample](https://github.com/aitorvs/android-architecture/tree/todo-rib) when I saw this open issue. It is still raw, as I am building it to get more insight on the architecture.

Check it our and please give any kind of feedback. As I am new to RIBs I might be using some anti-patterns :/

I have one question. What is the best practice to implement a view back-stack?

Thanks a lot for building RIBs. I like the concept a lot.

**Comment by dmarjanovic** [comment]
It would be great to have some RIBs with backstack (either RouterNavigator or ScreenStack based) working example or snippet from Uber team too so we can have shared knowledge from the source. I liked what @aitorvs shared. 👍

**Comment by dmarjanovic** [comment]
@aitorvs is it possible to "move" (integrate) todo sample from your fork to original repo? It seems like a nice example and having it in official repo would bring more visibility to RIBs in Android community.

**Comment by aitorvs** [comment]
Hey @AttwellBrian! Sure, i am still interested in getting this out.
I am totally fine with the name change. It makes sense.

**Comment by artman** [comment]
Closing out stale issues.
