### ISSUE TITLE
Add XIB option

### ISSUE THREAD

**Issue by kronik** [uber/RIBs#167]
Could you add an option on RIB creation to optionally add corresponding XIB file (if user ticks "Owns corresponding view"?

**Comment by sbarow** [comment]
Would this be something you would be interested in putting up a PR for?

**Comment by kronik** [comment]
[PR](https://github.com/uber/RIBs/pull/171)

**Comment by sbarow** [comment]
Thanks @kronik

**Comment by kronik** [comment]
👍🏻
