### ISSUE TITLE
RIB in UICollectionViewCell or UITableViewCell

### ISSUE THREAD

**Issue by kronik** [uber/RIBs#172]
Any particular ideas on how to attach / detach RIBs when user scrolls collection/table view with different RIBs inside cells?

**Comment by zethraeus** [comment]
You need to call through to the routing layer based on the UI callbacks in your Collection or Table View.

There are certainly times when this can be appropriate—when you truly have a set of scoped logic which happens to be displayed in a cell—but it should be pretty rare.

**Comment by artman** [comment]
Closing as answered / stale
