### ISSUE TITLE
Appearance has leaked

### ISSUE THREAD

**Issue by igordeoliveirasa** [uber/RIBs#174]
I have the following ribs' flow:

**Root (viewable) -> Home (viewable) -> Auth (not viewable) -> SignIn (viewable)** 

**Information:**
Auth is not viewable but its Router is a ViewableRouter, since it receives HomeViewController (such as LoggedIn of tutorial);

**When I am at HomViewController, I tap 'go to authentication area' button and it does the following:** 
- HomeViewController calls: listener.didSignInTap()
- HomeInteractor calls: router.routeToAuth()
- Since it's not a viewable RIB, when AuthRouter loads it calls: routeToSignIn()
- And finally, sign in view controller is displayed. Ok...
- When I tap on close button at SignInViewController, it calls: listener.didCloseTap.
- SignIn Interactor calls: listener.closeSignIn()
- Auth Interactor calls: router.detach, and after completion calls its: listener.closeAuth()
- Home Interactor calls: router.detach and stop there.

This flow is nice and is working as I expect, however, when I click at sign in button at Home again, I receive this:

> Assertion failed: <QualityDriver.HomeViewController: 0x7fbcd050ee40> appearance has leaked. Either its parent router who does not own a view controller was detached, but failed to dismiss the leaked view controller; or the view controller is reused and re-added to window, yet the router is not re-attached but re-created. Objects are expected to be deallocated at this time: NSMapTable {
}

**Comment by igordeoliveirasa** [comment]
I added a small project reproducing this here: git@gitlab.com:mobilevale/trying-ribs.git
Do not forget to run **pod install**.

**Comment by neakor** [comment]
I think this is the issue here 
> Auth is not viewable but its Router is a ViewableRouter
Auth should not be a ViewableRouter, since that means it's retaining the VC when it shouldn't.

**Comment by igordeoliveirasa** [comment]
@neakor but it's like LoggedIn RIB tutorial, which does not own view but was modified to handle a view. Please, help me! @neakor !

**Comment by igordeoliveirasa** [comment]
@neakor @sbarow I really think tutorial is not teaching correctly in LoggedInRouting. It worked there since there is no LoggedIn RIB detaching flow. If it had, it would crash too. So, tell me: The correct way is to let it as Routing instead of ViewableRouting and make it receive its parent view controller as a common parameter?

**Comment by neakor** [comment]
I'll find some time to download your sample code and look into it. The tutorial may be out of date. Thanks for being patient.

**Comment by neakor** [comment]
@igordeoliveirasa the tutorial code is actually wrong. View-less RIBs should **not** use the `ViewableRouter` or the `PresentableInteractor` base classes. Instead the router should inherit from `Router` and the interactor should inherit from `Interactor`. We'll correct the tutorial. Can you make this change to your local project and see?

**Comment by neakor** [comment]
Here's a pull request to fix the template https://github.com/uber/RIBs/pull/179

**Comment by neakor** [comment]
Here's the pull request to fix the tutorials https://github.com/uber/RIBs/pull/180

**Comment by neakor** [comment]
@igordeoliveirasa I've fixed the templates as well as the tutorials. Can you please update your local code and give it a try?

**Comment by igordeoliveirasa** [comment]
Yes, @neakor... I will do that as soon as possible!

**Comment by igordeoliveirasa** [comment]
@neakor I've checked ant its right now. Thank you.

**Comment by neakor** [comment]
Happy to help :)
