### ISSUE TITLE
[iOS] NavigationController as a RIB's View?

### ISSUE THREAD

**Issue by JakeSc** [uber/RIBs#176]
This question is similar to https://github.com/uber/RIBs/issues/163.

I have a RIB whose view is a UIViewController displayed as the rootViewController of a UINavigationController. Essentially, the Parent should present a UINavigationController like it would normally display any child View; and then the Child now has a view, as well as the capability to push children to the UINavigationController.

```
Parent
  |
  |__Child    (Its View is a UINavController(root: UIViewController) )
```

`ChildViewController` takes some input in its initializer, so I've made both `ChildViewController` and its wrapping `ChildNavigationController` abide by the `ChildPresentable` and `ChildViewControllable` protocols. Here's the NavigationController:

```
class ChildNavigationController: UINavigationController, ChildViewControllable, ChildPresentable {

    required init(menuModelStream: Observable<[ChildMenuModel]>) {

        // Save the ChildViewController so we can pass-through all ChildViewControllable and ChildPresentable calls to it
        self.mainView = ChildViewController(menuModelStream: menuModelStream)

        super.init(nibName: nil, bundle: nil)

        self.pushViewController(self.mainView, animated: false)
    }

    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }

    // ChildPresentable protocol is just a pass-through to the ChildViewController
    var listener: ChildPresentableListener? {
        get {
            return self.mainView.listener
        }
        set {
            self.mainView.listener = newValue
        }
    }

    private let mainView: ChildViewController
}
```

This accomplishes what I need to do (return up the NavController to the parent, display an actual root VC for the Child RIB, and allow for a nav stack for Child's children). However, it feels cumbersome and prone to code duplication. Is there an established paradigm for using UINavigationControllers in the middle of a RIB hierarchy?

Thanks!

**Comment by kronik** [comment]
From the previous discussion as I understand we have two options. And one of them might look like:

Place somewhere conformance to a ViewControllable protocol:

`extension UINavigationController: ViewControllable {
    public var uiviewController: UIViewController { return self }
    
    public convenience init(root: ViewControllable) {
        self.init(rootViewController: root.uiviewController)
    }
}
`

and then:

`    func routeToAnotherRIB(with param: String) {
        detachCurrentChild()

        let rib = anotherRIBBuilder.build(withListener: interactor, parameter: param)
        self.currentChild = rib
        attachChild(rib)
        
        let navController = UINavigationController(root: rib.viewControllable)
        
        viewController.replaceModal(viewController: navController)
    }
`

This code feels cleaner

**Comment by JakeSc** [comment]
Nice, thanks for the suggestion @kronik. Presumably then this navController will allow for pushing child RIBs' views to its stack. Perhaps we can have the AnotherRIB in your example hold a reference to (or even build) the NavigationController, so that it can use the NavigationController to push its own children.

**Comment by kronik** [comment]
@JakeSc  Definitely, you can return a navigationController from anotherRIBBuilder.build method in addition to a rib itself. Not sure if you need to hold an additional reference to it though because your view controller will do this for you and router just asks view controller to present child view controller for this rib.
