### ISSUE TITLE
Xcode tooling installation script issue

### ISSUE THREAD

**Issue by edrew08** [uber/RIBs#177]
I noticed that for the tooling installation script, `install-xcode-template.sh`, its success/failure seems to be dependent on the directory from which you run the script. For example, running `./install-xcode-template.sh`, when your current directory is `/tooling`, works fine. however, running `tooling/install-xcode-template.sh`, from `/ios`, doesn't succeed. the output says, `cp: *.xctemplate: No such file or directory`. The result is that the files don't get copied to `Xcode/Templates/File Templates/RIBs`. It appears that the `cp` commands in the script are relative to the current directory and not the script's source directory.

I can open a PR if desired.

**Comment by sbarow** [comment]
@edrew08 PR sounds good, thanks.

**Comment by edrew08** [comment]
Cool, [PR](https://github.com/uber/RIBs/pull/178) opened.

**Comment by edrew08** [comment]
PR merged, closing.
