### ISSUE TITLE
[Android][Tutorial] Tutorial 1: Compile error

### ISSUE THREAD

**Issue by namhvcntt** [uber/RIBs#181]
`void attachLoggedOut() {
        loggedOutRouter = loggedOutBuilder.build(getView());
        attachChild(loggedOutRouter);
        getView().addView(loggedOutRouter.getView());
    }
`
`
Error:(30, 57) error: incompatible types: RootView cannot be converted to ViewGroup
Error:(32, 18) error: cannot find symbol method addView(LoggedOutView)
`
I got this error when I am trying folow tutorial 1. (Source code in tutorial 2)
How to resolve this issue?

**Comment by artman** [comment]
@AttwellBrian, can you check this?

**Comment by almozavr** [comment]
@namhvcntt `class LoggedOutView extends LinearLayout` and not `extends View`
