### ISSUE TITLE
[Android] Example to demo the usage of screenstack

### ISSUE THREAD

**Issue by bangarharshit** [uber/RIBs#185]
Are you open to a PR for an example to show how to use `screenstack`? A very rough implementation - [ScreenStackImpl.java](https://github.com/bangarharshit/Ribs-ScreenStack-Impl).

The code covers just basic stack and state save/restoration and doesn't cover all the edge cases. Also, just a few transitions and not an exhaustive list.

**Comment by dmarjanovic** [comment]
It would be great to have it in official tutorial. 👍

**Comment by pcegarra** [comment]
im waiting for it too

**Comment by bangarharshit** [comment]
You can use the sample in my repo - To make it work with ribs, the high-level solution is to write a wrapper which detaches the child router when `screenstack.pop` is called.

**Comment by artman** [comment]
Closing out stale issues.
