### ISSUE TITLE
SWRevealViewController Integration Question

### ISSUE THREAD

**Issue by igordeoliveirasa** [uber/RIBs#189]
How to use it with SWRevealViewController?

**Comment by kronik** [comment]
I had the same question and tab bar controller is also under the question... The only one solution comes to my mind - both view controllers (presented and side) should be handled by one RIB. Any comments?

**Comment by dev4jam** [comment]
@igordeoliveirasa take a look at my sample: https://github.com/dev4jam/ToDo

**Comment by artman** [comment]
Closing out stale issues.
