### ISSUE TITLE
Reusing "Detaching Current Child" code...

### ISSUE THREAD

**Issue by igordeoliveirasa** [uber/RIBs#190]
The code below works fine for my routers. However, I've been having to copy and past it in each router just because the dismiss method at viewController (which is a ViewControllable type).

I need an idea about how could I extract the code below to a utility class or even an extension?

```swift
public func detachCurrentChild(completion: (() -> Void)?) {
        if let currentRoutingChild = self.children.last {
            self.detachChild(currentRoutingChild)
            if let currentViewableRoutingChild = currentRoutingChild as? ViewableRouting {
                self.viewController.dismiss(
                    viewController: currentViewableRoutingChild.viewControllable,
                    completion: completion
                )
            }
            else {
                completion?()
            }
        }
        else {
            completion?()
        }
    }
```

**Comment by kevinmun** [comment]
Can't you have that method in and extension of ViewableRouting? ViewableRouting has reference to ViewableControllable which can access the underlying viewcontroller. If that dismiss method is custom, then probably you can add it in as an extended method of viewControllable

**Comment by igordeoliveirasa** [comment]
I've tryied, but the problem is that normally, each view has their rules about dismissing...

**Comment by kevinmun** [comment]
I dont think that's a problem, you could have a ViewDismissable protocol that has a dismiss function and any viewcontrollable which can do a dismiss inherits from that , and they can implement their own dismiss

**Comment by artman** [comment]
Closing out stale issues.
