### ISSUE TITLE
Model and FormViewController

### ISSUE THREAD

**Issue by igordeoliveirasa** [uber/RIBs#191]
Let's suppose I have a model and a ModelFormViewController which is its current form...
Is it a good practice to let ModelFormViewController knows about this model or only its attributes? Letting the responsibility of model only to Interactor ... ?

**Comment by kevinmun** [comment]
This should be the responsibility of the presenter, which does not necessarily be your viewcontroller,  I would imagine, in MVVM's case, it would be your viewmodel.

**Comment by sbarow** [comment]
If the transformation of the model to a UI representable model/object is complex you can introduce a [Presenter](https://github.com/uber/RIBs/blob/master/ios/RIBs/Classes/Presenter.swift) & a [PresentableInteractor](https://github.com/uber/RIBs/blob/master/ios/RIBs/Classes/PresentableInteractor.swift) to do transformations. I don't think there is any issue with passing a model object to the `ViewController` if its just used for the UI. Any mutations and business logic performed on those models should still happen in the `Interactor`.

**Comment by igordeoliveirasa** [comment]
Awesome, @kevinmun  and @sbarow ! Thank you so much guys.

**Comment by igordeoliveirasa** [comment]
@kevinmun @sbarow in this case, interactor and viewController should have a declared model property at the top of class?

**Comment by artman** [comment]
If you have a Presenter, only the Interactor and Presenter would be aware of the model. The Presenter would transform the model into View updates and the View would just be a dumb representation not knowning anything about the model.
