### ISSUE TITLE
Creating a viewless RIB from template doesn't compile

### ISSUE THREAD

**Issue by edrew08** [uber/RIBs#192]
When creating a **viewless** RIB from the template, say for example you call it MyRib, the MyRibRouter class inherits from Router<MyRibInteractable>. The template has the MyRibRouter overriding Router's initializer:
`public init(interactor: InteractorType, viewController: ViewControllerType) { ... }` 

But that's the initializer for a `ViewableRouter`, a `Router's`  initializer is:
 `public init(interactor: InteractorType) { ... } ` 

The code doesn't compile because the initializer does not override a designated initializer from MyRibRouter's superclass. The issue seems to be related to PR #179 Maybe I don't understand those changes?

Steps to reproduce:
1. create a RIB from the template
2. uncheck Owns corresponding view
3. try to compile the code

I can open a PR if desired. Unless these changes were on purpose? @neakor

**Comment by neakor** [comment]
Good catch! I'll put up a fix.

**Comment by sbarow** [comment]
@edrew08 @neakor put up a change, it is intentional for the `Router` to have a `ViewController` passed in as a dependency in the template but just not to pass it up to its super class.

**Comment by neakor** [comment]
The template wasn't correctly updated. I just put up a PR to fix it.
