### ISSUE TITLE
How to use system controllers in iOS

### ISSUE THREAD

**Issue by kronik** [uber/RIBs#193]
It's not clear how to use system Safari, Message and Alert view controllers in iOS

**Comment by edrew08** [comment]
There is an example of a UIAlertController in Tutorial3-completed. Take a look at [TickTacToeViewController.swift](https://github.com/uber/RIBs/blob/master/ios/tutorials/tutorial3-completed/TicTacToe/TicTacToe/TicTacToeViewController.swift).

**Comment by kronik** [comment]
Got it. Thanks.
