### ISSUE TITLE
Some improvements to the wiki docs

### ISSUE THREAD

**Issue by dzzh** [uber/RIBs#195]
Hi guys,

Thanks for open-sourcing the RIBs architecture and tooling around it, I had fun time reading about the challenges you face and how this architecture helps you to address them. 

While getting through the documentation available in this repo and working with the tutorials, I found that  I could improve the language a bit to make the narration somewhat smoother. I'm not a native English speaker and maybe some of the changes I suggest are not correct, but I still believe I managed to make the Home wiki page look slightly better.

Please have a look at this commit and either cherry-pick it or manually copy the changes you agree with to the main wiki (I can't edit it directly).

https://github.com/dzzh/RIBs-wiki/commit/592c6fca0adbd6c5fe0fb8db358bbe0459c076b8

If you agree with the changes I suggest, I'll be happy to update the rest of the wiki pages in a similar manner. Let me know if you want me to do so.

**Comment by kovpas** [comment]
Looks good to me, @artman could you please also have a look?

**Comment by artman** [comment]
So sorry for the slow reply. Looking now.

**Comment by artman** [comment]
Thanks for the contribution! Copied it over to the wiki with some modifications. Would love to receive more of these for sure!

**Comment by dzzh** [comment]
Thanks, stay tuned :)
