### ISSUE TITLE
I need some tips for testing ViewControllers

### ISSUE THREAD

**Issue by igordeoliveirasa** [uber/RIBs#198]
I know that here is not the best place to make this question, however, since one of the RIBlets purposes is to split mvc layers in order to make them more testable, I'd like to know how could I test UIViewControllers, since there are some methods and properties that really needs a real UI flow, like self.presentedViewController, commonly used at dismiss method described on RIBlets tutorials ?

Thanks in advance...

**Comment by artman** [comment]
Unit tests are good to test input and output of each component. ViewControllers and Views usually need more than that. [Snapshot testing](https://github.com/uber/ios-snapshot-test-case) can be used for verifying that views render correctly, and [UITests](https://developer.apple.com/library/content/documentation/DeveloperTools/Conceptual/testing_with_xcode/chapters/09-ui_testing.html) (sorry, both are iOS examples) can help you create integration tests that go beyond unit tests.
