### ISSUE TITLE
Intercepting back button

### ISSUE THREAD

**Issue by igordeoliveirasa** [uber/RIBs#204]
When we have a pushed view controller, how is the best practice to intercept navigation back button so as to call interactor -> router ?

**Comment by edrew08** [comment]
Maybe it depends on how you implement it, but what would you be routing to?  Wouldn't the RIB that you are popping to still be attached to its parent? The view your popping to would still be in the navigation controller's stack, right?

**Comment by edrew08** [comment]
If what your trying to do is detach the router for the RIB that is being popped, one option is the following. 

In the view controller that is being popped:
```swift   
override func viewDidDisappear(_ animated: Bool) {
    super.viewDidDisappear(animated)
    if isMovingFromParentViewController {
        listener?.didMoveFromParent()
    }
}
```

Then your listener can delegate to the parent router that has the child router attached and it can detach your child router for the RIB that is being popped.
