### ISSUE TITLE
Running the Xcode template installation script

### ISSUE THREAD

**Issue by edrew08** [uber/RIBs#209]
It appears that the only way to run the Xcode template installation script is to clone or download the RIBs project and then run `install-xcode-template.sh`. It seems like the templates and the installation script should also be part of the podspec, that way a user can run the template installation script after the pod install without also having to download the project separately, or am I missing something?

**Comment by artman** [comment]
Post install hooks in Cocapods have been deprecated. Also, we wouldn't want to change the Xcode environment simply when installing a pod, so yes, the only way to install the templates is the check out the RIBs repo and run the install script.

**Comment by edrew08** [comment]
I wasn't thinking in terms of automating the template installation script process within cocoapods. I was more just thinking that there should be a way to install to the templates without also having to download project separately.
