### ISSUE TITLE
Recommended way to reuse / subclass Workflows?

### ISSUE THREAD

**Issue by jbrophy17** [uber/RIBs#212]
Is there a recommended way to subclass `Workflow` so that the same core steps can be reused for multiple `Workflow`s? 

When using them for Deeplinks, I've found that most of my `Workflow`s all start with the same steps (waiting for initial data, waiting for the user to be logged in, routing to home) and then continue from that step to do specific logic. From what I have seen, there isn't a great way to re-use these core steps across multiple `Workflow`s

One option, I think, would be to subclass and then fork `self` in the `init()`, but this would lead to calling `.commit()` on your workflow twice (once in the `super.init()` and once on the fork), which leads to multiple subscriptions and can cause issues like #211. (Which isn't a dealbreaker, but does make it seem like there could be a better solution) 

But maybe I'm missing something, any suggestions?

**Comment by AttwellBrian** [comment]
Why not define a reusable method somewhere that returns the first few steps? Then inside each workflow you write:

```
  @Override
  protected Step<Step.NoValue, MainActionableItem> getSteps(
      RootActionableItem rootActionableItem, VoipDeeplink voipDeeplink) {
    return new CommonSteps()
        .doCommonThing(rootActionableItem)
        .onStep((noValue, rootSignedInActionableItem) -> rootSignedInActionableItem.goToMain())
        .onStep(new GoToVoipCallScreen())
        .onStep(new DoSomethingSpecial());
  }
```

Ie: why not use composition instead of inheritance?

**Comment by jbrophy17** [comment]
Yeah, good point, I can just do something like that. I was just curious because it seemed like a natural extension of the `Workflow` would be some way of chaining them together. Not necessarily inheritance, but a way to compose a complex `Workflow` by building off of an existing one, without adding a static accessor for the `Step`s.

But that's a pretty minor complaint! I can work with your suggestion, thanks!
