### ISSUE TITLE
Deprecate error prone check in favor of check in AutoDispose

### ISSUE THREAD

**Issue by bangarharshit** [uber/RIBs#215]
AutoDispose has now an error-prone check to detect memory leak - [wiki](https://github.com/uber/AutoDispose/wiki/Error-Prone-Checker).  

It can be easily configured for ribs:
```groovy
    options.compilerArgs += [
            "-XepOpt:UseAutoDispose:ClassesWithScope=" +
                    "com.uber.rib.core.Router," +
                    "com.uber.rib.core.Presenter," +
                    "com.uber.rib.core.Interactor," +
                    "com.uber.rib.core.Worker"
    ]
```

It is updated with the new `as` API and can be kept updated with further changes in AutoDispose.

Steps involved:
1. Update `AutoDispose` to `0.6.0`.
2. Delete the check in the repo and set up the correct configuration in the leak analysis demo.

**Comment by jbarr21** [comment]
Done in #398
