### ISSUE TITLE
[Android] Tutorial 1 import error SDK path

### ISSUE THREAD

**Issue by datnt1987** [uber/RIBs#218]
Hi, when importing project tutorial1 into android studio, it displayed error when I did step 1:

> Let’s try installing the tutorial1 starter app to ensure your environment is up and running. Use Android Studio or execute the following command: ./gradlew :tutorials:tutorial1:installDebug

> A problem occurred configuring project ':demos:memory-leaks'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

After checking in android studio preferences, sdk.dir already point correct sdk path. Please help me.

**Comment by datnt1987** [comment]
I resolved it.

**Comment by qichuan** [comment]
I encountered the same problem. @datnt1987 How did you resolve it?
