### ISSUE TITLE
[Android] How to use RecyclerView with RIBs?

### ISSUE THREAD

**Issue by Hayashi2026** [uber/RIBs#220]
When I use  recyclerView, I got problems. I don't know how to bind onClickListener of a  childview' button. In my recyclerView's adapter, I create child view, and I need to bind onClickListen in it. In this case, I can't bind onClickListener by RxView, cause the childview don't created until we scroll to it. and I can't get interactor in view. Could I access Interactor directly in View? Cause view impletement presenter. There are no examples of recyclerView in tutorials.

**Comment by asvid** [comment]
Your adapter can have a subject that would be called each time item is clicked
`holder.itemView.setOnClickListener {
            onClickSubject.onNext(item)
        }`
and then you can add method to Presenter interface
` fun listItemClick(): Observable<Device>`

so in View you just return adapters Subject

At least it is how I did it :)

**Comment by Hayashi2026** [comment]
@asvid Thank you for answer my question. You answer solves my problem， I think it's a good way to do it.

**Comment by artman** [comment]
Thanks for helping out @asvid!
