### ISSUE TITLE
[iOS] Passing data up

### ISSUE THREAD

**Issue by tailec** [uber/RIBs#232]
I have this RIBs tree structure:

![graph](https://user-images.githubusercontent.com/10499966/38175663-1243b9c6-35d8-11e8-8e69-cb9432651e23.png)

The issue I'm having is finding a good way of passing data from children components (D, E, F) to component in another "subtree" (G). 

Currently, I'm passing this data through every parent component (for example D -> C -> B -> A -> Root) using Listeners and then I'm using Rx stream to pass data from Root to G. 

This creates a lots of boilerplate and I wonder if there's a better way of doing it.

**Comment by rendecano** [comment]
Maybe save the data to a persistent storage(D) (shared pref, DB, etc.) and access it from the subtree (G)? (Just throwing suggestions.. :D )

**Comment by dev4jam** [comment]
@tailec It seems the right way because otherwise, you'll couple your RIBs or introduce implicit "global state" (like a singleton). Your current idea keeps all RIBs decoupled and thus testable.

**Comment by dimaosa** [comment]
@tailec You could pass **Mutable** rx stream from Root to children (D, E, F), and make changes in D, E, F, after that pass **NonMutable** Rx Stream to G (if you need only listen). So in that way you don't need to use Listeners in A, B, C
