### ISSUE TITLE
Combine MVP and RIBs in one project

### ISSUE THREAD

**Issue by AndroidStudentClub** [uber/RIBs#233]
I have project with 2 parts. One part of this app will be developed by other team. They decided to use RIBs architecture. But in my module I want to use MVP and Clean Architecture. So, my question is: Is it possible to combine two modules MVP and RIBs? How would this work?

**Comment by Zhuinden** [comment]
RIB architecture is cleaner than MVP.

Also, "clean architecture" just says you should have domain-specific models and mappers inbetween, and RIBs don't stop you from that.

**Comment by AttwellBrian** [comment]
Clean Architecture and MVP are principles and architectural patterns. No reason RIBs can't be used to implement clean architecture. Similarly depending on how you use the presenter, RIBs subsume the features of the MVP pattern.

I'm guessing you mean the other team is using a separate MVP framework? If you need the two frameworks to interop then you can introduce a compatibility layer that allows MVPControllers to attach RIBs or vise versa. RIBs pull most of their dependencies via DI so it is very possible to attach RIBs into non-RIBs with some work.

However, your code base will be easier to understand and maintain if you minimize the number of technologies you use. If your codebase uses both MVPControllers and RIBs then you have more things to worry about. At the very least, to keep things sane you may want to say: screen A is built with RIBs and screen B is built with MVPControllers.

**Comment by AttwellBrian** [comment]
Also, check out "What is the difference between RIBs and MV*/VIPER" on the home page.
