### ISSUE TITLE
Using fragments in RIBs

### ISSUE THREAD

**Issue by DebashisPorter** [uber/RIBs#239]
Hi, we have an existing app which we are planning to move into RIBs architecture but we want to use fragments in that. So just wanted to know can we use fragments in RIBs and if yes how and how difficult it is to handle fragments in RIBs?

**Comment by Zhuinden** [comment]
Fragments live their own life, so I'm sure it's tricky.

I have not actually used RIBs though, but you most likely won't be able to use hacky things like `fragmentTransaction.addToBackStack(null)`.

**Comment by DebashisPorter** [comment]
Yeah, RIBs handles attaching and detaching of views. Also it maintains the backstack, so if i will use fragment then i think instead of attaching and detaching i will have to replace fragments and yeah as you mentioned i will have to handle fragment backstack.

**Comment by Zhuinden** [comment]
You should probably use views with inflated fragments.

**Comment by DebashisPorter** [comment]
Yeah, thanks Zhuinden...that should work, will do that.
