### ISSUE TITLE
[Android] Improve the RIB generator plugin with the ability to create a "ViewProvider"/"Screen" component

### ISSUE THREAD

**Issue by jorgecoca** [uber/RIBs#246]
Currently, the "New RIB..." plugin for Android only comes with two options:

- A checkbox for creating an optional view and presenter
- A checkbox for using Kotlin (in experimental phase)

I think it would be really convenient to add a third option, in the form of a checkbox, that lets you create a "Screen"/"ViewProvider" class for those projects using the **ScreenStackBase** class. I find myself writing the same boilerplate for this classes pretty much all the time.

If you think this is a good idea, I can work on a pull request.

**Comment by ermik** [comment]
I think further bloat in number of options on the template screen is not necessarily a good thing, but an example that you can share with the community (via Medium perhaps? 😉) will help RIB adoption everywhere! (Certainly will help me to get going, totally self-serving, I know.)
