### ISSUE TITLE
Any plans to publish ribs-0.9.2 to mvn?

### ISSUE THREAD

**Issue by jeffreyrr** [uber/RIBs#249]
Currently stuck on version 0.9.1 on Android via maven central. Any plans to bump this to 0.9.2?

https://mvnrepository.com/artifact/com.uber.rib/rib-android

**Comment by AttwellBrian** [comment]
I was under the impression that 0.9.1 and 0.9.2 only differ in the iOS implementation. Makes sense to release the Android version once there is new code in it.

Maybe we shouldn't be keeping the iOS and Android numbers in sync because it causes confusion like this ¯\_(ツ)_/¯
