### ISSUE TITLE
Unittests boilerplate code

### ISSUE THREAD

**Issue by dev4jam** [uber/RIBs#251]
How do you generate mocked objects code? Noticed that every mock class contains repeating handler  + counter + function call sequence. Does anyone have sourcery template?

**Comment by dev4jam** [comment]
Ok... I've implemented several custom Sourcery templates based on AutoMockable for Presentable, ViewableRouting, and Interactable... Seems like this is enough to cover 90% of the boilerplate mocking code.

**Comment by sbarow** [comment]
@dev4jam had a look at this today, what I noticed is `sourcery` won't be able to generate the inherited protocol methods for `Presentable`, `ViewableRouting` etc. unless you include the source for `RIBs` in the sources argument.

Example using `Carthage`, same could be done with `Cocoapods`:
`sourcery --config PATH/TO/.sourcery.yml`
```
sources:
	- {TargetSourcer}
	- ../Carthage/Checkouts/RIBs/ios/RIBs/Classes
...
```

Let me know if that helps?

**Comment by artman** [comment]
Closing as answered
