### ISSUE TITLE
iOS Tutorial 4 Complete - deeplinking not working

### ISSUE THREAD

**Issue by lmrkllc** [uber/RIBs#258]
I ran iOS Tutorial 4 - Complete on iPhone 6s plus and tried to deeplink but keep getting the following error:

Thread 1: EXC_BAD_ACCESS (code=1, address=0x0)

I tried deleting  app and re-installing but no luck.

Sometimes it works when app is running.

Thank you,

Kenny

**Comment by artman** [comment]
Could you post the stack trace?

**Comment by lmrkllc** [comment]
@artman sure here it is.  thank you!  

Incident Identifier: 2F14DF98-15D7-4BFF-A555-E2850FA2DB5A
CrashReporter Key:   4045dc79bcd58f176cf5fec24c8906a848373093
Hardware Model:      iPhone8,2
Process:             TicTacToe [1617]
Path:                /private/var/containers/Bundle/Application/39444625-B486-4C02-9CE3-7D83E4BC1969/TicTacToe.app/TicTacToe
Identifier:          com.ubercab.TicTacToe
Version:             1 (1.0)
Code Type:           ARM-64 (Native)
Role:                Foreground
Parent Process:      launchd [1]
Coalition:           com.ubercab.TicTacToe [1013]


Date/Time:           2018-05-29 16:43:32.9904 -0400
Launch Time:         2018-05-29 16:43:18.0946 -0400
OS Version:          iPhone OS 11.3.1 (15E302)
Baseband Version:    4.56.00
Report Version:      104

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype: KERN_INVALID_ADDRESS at 0x0000000000000000
VM Region Info: 0 is not in any region.  Bytes before following region: 4377657344
      REGION TYPE                      START - END             [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                 0000000104edc000-0000000104f20000 [  272K] r-x/r-x SM=COW  ...app/TicTacToe

Termination Signal: Segmentation fault: 11
Termination Reason: Namespace SIGNAL, Code 0xb
Terminating Process: exc handler [0]
Triggered by Thread:  0

Filtered syslog:
None found

Thread 0 name:  Dispatch queue: com.apple.main-thread
Thread 0 Crashed:
0   libswiftCore.dylib            	0x00000001059bbaa4 0x105700000 + 2865828
1   TicTacToe                     	0x0000000104ee8c98 0x104edc000 + 52376
2   TicTacToe                     	0x0000000104ee8c98 0x104edc000 + 52376
3   UIKit                         	0x000000018e42cacc __58-[UIApplication _applicationOpenURLAction:payload:origin:]_block_invoke + 880
4   UIKit                         	0x000000018e42c440 -[UIApplication _applicationOpenURLAction:payload:origin:] + 596
5   UIKit                         	0x000000018e048e20 -[UIApplication _handleNonLaunchSpecificActions:forScene:withTransitionContext:completion:] + 5468
6   UIKit                         	0x000000018e011f04 -[__UICanvasLifecycleMonitor_Compatability activateEventsOnly:withContext:completion:] + 1632
7   UIKit                         	0x000000018eca772c __82-[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:]_block_invoke + 296
8   UIKit                         	0x000000018e011268 -[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:] + 432
9   UIKit                         	0x000000018ea8c9b8 __125-[_UICanvasLifecycleSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:]_block_invoke + 220
10  UIKit                         	0x000000018ebdaae8 _performActionsWithDelayForTransitionContext + 112
11  UIKit                         	0x000000018e010c88 -[_UICanvasLifecycleSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:] + 248
12  UIKit                         	0x000000018e010624 -[_UICanvas scene:didUpdateWithDiff:transitionContext:completion:] + 368
13  UIKit                         	0x000000018e04e3b0 -[UIApplicationSceneClientAgent scene:handleEvent:withCompletion:] + 468
14  FrontBoardServices            	0x0000000186c74f24 __80-[FBSSceneImpl updater:didUpdateSettings:withDiff:transitionContext:completion:]_block_invoke.362 + 212
15  libdispatch.dylib             	0x0000000183d68ae4 _dispatch_client_callout + 16
16  libdispatch.dylib             	0x0000000183d701f4 _dispatch_block_invoke_direct$VARIANT$mp + 224
17  FrontBoardServices            	0x0000000186ca8878 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 36
18  FrontBoardServices            	0x0000000186ca851c -[FBSSerialQueue _performNext] + 404
19  FrontBoardServices            	0x0000000186ca8ab8 -[FBSSerialQueue _performNextFromRunLoopSource] + 56
20  CoreFoundation                	0x000000018441f404 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
21  CoreFoundation                	0x000000018441ec2c __CFRunLoopDoSources0 + 276
22  CoreFoundation                	0x000000018441c79c __CFRunLoopRun + 1204
23  CoreFoundation                	0x000000018433cda8 CFRunLoopRunSpecific + 552
24  GraphicsServices              	0x000000018631f020 GSEventRunModal + 100
25  UIKit                         	0x000000018e31d78c UIApplicationMain + 236
26  TicTacToe                     	0x0000000104ee9adc 0x104edc000 + 56028
27  libdyld.dylib                 	0x0000000183dcdfc0 start + 4

Thread 1:
0   libsystem_pthread.dylib       	0x000000018409bb04 start_wqthread + 0

Thread 2:
0   libsystem_kernel.dylib        	0x0000000183efdd84 __workq_kernreturn + 8
1   libsystem_pthread.dylib       	0x000000018409beb4 _pthread_wqthread + 928
2   libsystem_pthread.dylib       	0x000000018409bb08 start_wqthread + 4

Thread 3:
0   libsystem_kernel.dylib        	0x0000000183efdd84 __workq_kernreturn + 8
1   libsystem_pthread.dylib       	0x000000018409c0a0 _pthread_wqthread + 1420
2   libsystem_pthread.dylib       	0x000000018409bb08 start_wqthread + 4

Thread 4 name:  com.apple.uikit.eventfetch-thread
Thread 4:
0   libsystem_kernel.dylib        	0x0000000183edbe08 mach_msg_trap + 8
1   libsystem_kernel.dylib        	0x0000000183edbc80 mach_msg + 72
2   CoreFoundation                	0x000000018441ee40 __CFRunLoopServiceMachPort + 196
3   CoreFoundation                	0x000000018441c908 __CFRunLoopRun + 1568
4   CoreFoundation                	0x000000018433cda8 CFRunLoopRunSpecific + 552
5   Foundation                    	0x0000000184db1674 -[NSRunLoop+ 34420 (NSRunLoop) runMode:beforeDate:] + 304
6   Foundation                    	0x0000000184db151c -[NSRunLoop+ 34076 (NSRunLoop) runUntilDate:] + 148
7   UIKit                         	0x000000018e0027e4 -[UIEventFetcher threadMain] + 136
8   Foundation                    	0x0000000184ec1efc __NSThread__start__ + 1040
9   libsystem_pthread.dylib       	0x000000018409d220 _pthread_body + 272
10  libsystem_pthread.dylib       	0x000000018409d110 _pthread_body + 0
11  libsystem_pthread.dylib       	0x000000018409bb10 thread_start + 4

Thread 5:
0   libsystem_kernel.dylib        	0x0000000183efdd84 __workq_kernreturn + 8
1   libsystem_pthread.dylib       	0x000000018409beb4 _pthread_wqthread + 928
2   libsystem_pthread.dylib       	0x000000018409bb08 start_wqthread + 4

Thread 6:
0   libsystem_pthread.dylib       	0x000000018409bb04 start_wqthread + 0

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x4000000000000016   x2: 0x00000001844f6d74   x3: 0x0000000105a49d20
    x4: 0x0000000000000007   x5: 0x0000000000000000   x6: 0x0000000000000000   x7: 0x0000000000000000
    x8: 0x0000000000000000   x9: 0x0000000000000000  x10: 0x0000000152872c00  x11: 0x000000370000007f
   x12: 0x0000000152872c00  x13: 0x00000001b667f610  x14: 0x0000000000000000  x15: 0x018d7401018d74c0
   x16: 0x00000001059bba68  x17: 0x0000000184341980  x18: 0x0000000000000000  x19: 0x0000000000000000
   x20: 0x00000001c428f690  x21: 0x0000000000000000  x22: 0x0000000000000000  x23: 0x000000018ed98494
   x24: 0x0000000151d025e0  x25: 0x00000001c0076c40  x26: 0x00000001aec85758  x27: 0x0000000000000000
   x28: 0x00000000000000e0   fp: 0x000000016af21870   lr: 0x0000000104ee8c98
    sp: 0x000000016af21860   pc: 0x00000001059bbaa4 cpsr: 0x60000000

**Comment by lmrkllc** [comment]
Yeah, weird.  I tried to cleaning project, removing derived data and building but no luck.  :-(  Let me delete the project and start over and see if that helps.  Thank you for looking into it.  @artman

**Comment by lmrkllc** [comment]
hi @artman,  I upgraded to iOS 11.4 and all is well now.   thank you for all your help!!

-Kenny
