### ISSUE TITLE
[iOS] Implementing UITabBarController

### ISSUE THREAD

**Issue by shubham01** [uber/RIBs#259]
I am getting confused while creating UITabBarController.

Assuming it has 2 tabs, both of which are RIBs:

- When should the child RIBs be attached?
- Can all of them be active at the same time?
- When should the tab bar controller set its view controllers?

**Comment by dev4jam** [comment]
Hi @shubham01, I would attach all child RIBs on activation. Definitely, you can activate all of them and you can set child view controllers on activation too. You may want to check this example here https://github.com/dev4jam/ToDo. There is a very similar use-case with Drawer (side menu) which requires content and menu view controllers (and RIBs) be set on activation.

**Comment by shubham01** [comment]
@dev4jam Thanks a ton for creating this app!
