### ISSUE TITLE
[Question] How to inject dependencies into view class?

### ISSUE THREAD

**Issue by vchernyshov** [uber/RIBs#261]
How to inject dependencies into view class?
Should I create new Dagger component and module with view dependencies and than directly instantiate component inside view and call inject method?

**Comment by dron247** [comment]
Do not do that! Always use a presenter to communicate with a view! You can pass through presenter methods whatever listener you want, or get an observable etc. And you already have a link on presenter inside your interactor ready to do the job. Also keep the view as dumb as possible.

**Comment by vchernyshov** [comment]
"Also keep the view as dumb as possible" - What are you talking about, view implements presenter interface in this architecture! I need to provide view-related dependencies, such as adapter, that uses rx diff utils, with its own schedulers, how should I do this, create dependencies directly in the view - as for me, not good idea.

**Comment by dron247** [comment]
You must inject them through presenter method, the view is being inflated inside the builder, you have no access to its constructor(sure you can create it manually in that method).
If you need a view that smart and decoupling to smaller ribs is not an option just put a method or property inside your presenter like
```kotlin
interface IWhateverPresenter {
    val title: String
    val adapter: IMySuperAdapter
    fun backflip(anotherStuff: Stuff? = null): Whatever
}
```
Inside your interactor
```kotlin
    @Inject
    lateinit var presenter: IWhateverPresenter

    @Inject
    lateinit var adapter: IMySuperAdapter

    override fun didBecomeActive() {
        super.didBecomeActive()
        presenter.adapter = adapter
        presenter.backflip()
    }
```
Thats it, easy, works, bulletproof

**Comment by melbystyle** [comment]
Whats the suggested way to do this?

**Comment by ermik** [comment]
You guys should watch out for when [uber/needle](https://github.com/uber/needle) drops.

**Comment by sbarow** [comment]
@ermik looks like this is an Android question, `needle` is for iOS, the Android counterpart is [uber/motif](https://github.com/uber/motif)

**Comment by ermik** [comment]
> There is an android counterpart? :mind_blown:

**Comment by artman** [comment]
Closing thread as stale.
