### ISSUE TITLE
[QUESTION] Is it possible to make a RIB or a set of RIBs reusable in multiple projects

### ISSUE THREAD

**Issue by MathieuBrousseIDO** [uber/RIBs#263]
Hi guys.
I'm currently evaluating mobile architectures solutions and found RIBs, it sounds very promising and it look like it can cover many of my requierments and i'm thinking of testing it really soon.
One information i couldn't find, is the reusability of modules built with RIB across differents applications.
So my question is : is it possible to develop RIB in dedicated projects and use them as dependencies for applications as dynamic libraries ?

**Comment by pbrazdil** [comment]
This is exactly the right use case of this architecture.

Each RIB has independent inputs and outputs. So you can easily put it in the separate module and use it across multiple apps.

**Comment by MathieuBrousseIDO** [comment]
That's what i was thinking.
I'm gonna do some tests but is there a recommandation on how to share RIBs across multiple apps ?

**Comment by pbrazdil** [comment]
Generals rules apply, I remember there are some wwdc videos on this topic.

**Comment by MathieuBrousseIDO** [comment]
Ok
