### ISSUE TITLE
Detaching hook

### ISSUE THREAD

**Issue by igordeoliveirasa** [uber/RIBs#269]
Does a routing know when it is going to be detached?

It's because I have a Routing (A) that contains 2 new routing being shown at the same time. When Routing A Listener closes Routing A, its 2 routings keeps in memory causing memory leak. These 2 routings are like: side menu and main viewController.

**Comment by ermik** [comment]
Afaik you have two options:
1. Propagate the signal up the listener chain.
1. Propagate the change to the state of the application via Rx, which will loop back to all components listening for state changes, and then you can unmount a branch of the tree in one of the parents (watch out for memory leaks).
