### ISSUE TITLE
How to Handle Util with a context param?

### ISSUE THREAD

**Issue by Hayashi2026** [uber/RIBs#271]
I have a DisplayUtil class with a static method,  but i can't get a context in an Interactor. And I don't want to keep a static context in DisplayUtil class and then inject it to Interactor. Is there any other way to handle it. How uber developer team to handle such problems?

```
public class DisplayUtil {
    public static int dip2px(Context context, float dpValue) {
        final float scale = context.getResources().getDisplayMetrics().density;
        return (int) (dpValue * scale + 0.5f);
    }
}
```

**Comment by Hayashi2026** [comment]
`public class DisplayUtil
{

    public static int screenWidthPx; //屏幕宽 px
    public static int screenhightPx; //屏幕高 px
    public static float density;//屏幕密度
    public static int densityDPI;//屏幕密度
    public static float screenWidthDip;//  dp单位
    public static float screenHightDip;//  dp单位



    /**
     * 根据手机的分辨率从 dp 的单位 转成为 px(像素)
     */
    public static int dip2px(Context context, float dpValue) {
        final float scale = context.getResources().getDisplayMetrics().density;
        return (int) (dpValue * scale + 0.5f);
    }

    /**
     * 根据手机的分辨率从 px(像素) 的单位 转成为 dp
     */
    public static int px2dip(Context context, float pxValue) {
        final float scale = context.getResources().getDisplayMetrics().density;
        return (int) (pxValue / scale + 0.5f);
    }

}`

**Comment by DebashisPorter** [comment]
You can provide the context from the Builder(say RootBuilder) so that you can inject it(construction injection) into your DisplayUtil class.
Now when you will inject DisplayUtil in the interactor, Dagger will see the Dependency of Context and it will pass it through your Builder.
