### ISSUE TITLE
What's the best way to call RIBs in applicationWillTerminate(:) ?

### ISSUE THREAD

**Issue by jerryzhoujw** [uber/RIBs#272]
Hi, 

   I would like to do extra save in `applicationWillTerminate(:)` .  In where I only have a `LaunchRouting`
  Should I add `saveData()` in or somewhere else?  
   And current my `saveData()` is in `RootComponent`.

**Comment by ninokierulf** [comment]
Have you found the solution to your question? if so, please share and close the issue.

These are some suggestions I came up with.
- one suggestion is to treat it like a rib-workflow (see tutorial 4)
- another is to be able to pass the save request through the ribs tree but i dont think it's an elegant solution
- another option is to use rx application stream that listens to `applicationWillTerminate(:)` that way, saving will happen on the interactor where you want to save, you could subscibe to something like `rx.applicationTerminate` but you should have a save trigger stream that combines normal save requests with you applicationWillTerminate save request. Interactor should only know that there is a save action being requested, it doesn't need to know if it was a button that triggered the request or it came from some event like `applicationWillTerminate`

PS: Im not from uber so I may not know what I'm talking about and there might be better solutions

**Comment by jerryzhoujw** [comment]
@ninokierulf  actually,  I'm not using ribs for a while, and I can't remember how I handle this question at last. I can close this since I didn't use RIBs now.
