### ISSUE TITLE
Best practices for using UITabViewController

### ISSUE THREAD

**Issue by igordeoliveirasa** [uber/RIBs#273]
What's the best practices for this use case?

**Comment by sbarow** [comment]
Its just a ViewController so you can use it with RIBs. The only thing to think about is the data which is used by the ViewController. Generally you want to "transform" data from your Interactor which would be loading/requesting data from somewhere to the ViewController which could be done in multiple ways e.g having a separate Presenter between Interactor & ViewController, directly in the ViewController or having a separate object specifically for data transformation.
