### ISSUE TITLE
Using googleMaps on Android with RIBs

### ISSUE THREAD

**Issue by alterevit** [uber/RIBs#276]
Hi, we have an application on the RIBs architecture,
We need to embed maps into the application, and we planned to use GoogleMap, but they have to map MapView to the life cycle of the activity or fragment.

The above example of use in the tutorial does not work at all in this architecture
https://developers.google.com/maps/documentation/android-sdk/map-with-marker

using `<fragment>` in view or adding to a fragment through a transaction like this:

```
override fun onAttachedToWindow () {
        super.onAttachedToWindow ()
        (activity as RootActivity) .supportFragmentManager
            .beginTransaction ()
            .replace (R.id.mapContainer, SupportMapFragment.newInstance ())
            .commit ()
    }
```

causes the application to crash.

How to adapt GoogleMap to the RIB architecture or what other maps api can I use that do not pipe the settings on the device of a separate application with the maps and fit into the architecture of the ribs?

**Comment by asvid** [comment]
Why you don't use MapView in RIB layout?https://developers.google.com/android/reference/com/google/android/gms/maps/MapView

**Comment by artman** [comment]
Closing as stale.
