### ISSUE TITLE
Tree creation tool

### ISSUE THREAD

**Issue by davidseek** [uber/RIBs#277]
Hey guys.

First of all thanks for the open source.
Loved the tutorials. Very easy to understand.

Question tho. 
I expect that your tool to create Tree is an intern thing?
Could you open source it? Or sell it? Or provide a link?

I'm using mind node, 
but I prefer your way of handling the parent nesting.

![state](https://user-images.githubusercontent.com/17073950/46552760-8f4f8800-c890-11e8-8620-3f309331417e.gif)

**Comment by kovpas** [comment]
As far as I know, it's [lucidchart](https://www.lucidchart.com/) + basic img-to-gif converter :)

**Comment by davidseek** [comment]
Sweet. It is lucidchart. Tried it out and got the desired results! Thank you!

**Comment by ermik** [comment]
What about the iOS debugger webapp that shows RIB's attached/detached?

**Comment by davidseek** [comment]
That would be epic to know.

**Comment by ermik** [comment]
@artman was using it for [his Devoxx presentation](https://youtu.be/FfwZSk6VRVY?t=1639):
![image](https://user-images.githubusercontent.com/229435/46609793-f65e7e00-cad6-11e8-87f2-84f6c3a576ce.png)

**Comment by sbarow** [comment]
I don't believe we have any plans to open-source the tool.
cc @rudro

**Comment by ermik** [comment]
Would be nice to officially float the idea and have it considered as a sleek DevTool complementary to the RIBs framework. If there is IP that is part of the tool that is an issue here — some sort of nod to the community, so that we could build our own, is required. It isn't that hard, is it?

**Comment by kovpas** [comment]
To be completely honest, the tool is very nice for presentation purposes, but I've never used it during development. There might be a use-case to catch memory leaks (i.e. RIBs are staying in memory, while they should be deallocated), but there's already a [memory leak detector](https://github.com/uber/RIBs/tree/master/ios/RIBs/Classes/LeakDetector) available in RIBs.

**Comment by ermik** [comment]
(Just one more observation before I surrender.) From a perspective of an experienced iOS engineer, let alone someone who is part of Uber organization — I can imagine — it is not terribly helpful to have this during dev. Especially if one is not working on the core tree, (e.g. creating plugins). If you consider someone just discovering RIBs with a desire to learn about clean, scalable architecture such visualizer would be very helpful. It delivers a novice RIB user with a helpful perspective on all of the boilerplate.

**Comment by kovpas** [comment]
That's a good point. Let's wait for @rudro or @artman to answer if there are any plans on open-sourcing the tool.

**Comment by artman** [comment]
We did want to, but currently don't have enough time to devote to this.

**Comment by srea** [comment]
@artman @ermik @rudro  I published RIBs live visualizer. but  it is rough...
https://github.com/srea/RIBsTreeViewerClient
