### ISSUE TITLE
[Question] Passing data across RIBs

### ISSUE THREAD

**Issue by gogovan-terrypang** [uber/RIBs#296]
Given that
1.  there are two RIBs modules, `A` and `B`
2. `B` is attached to `A` and `A` presents `B`
3. `B` reads data from `A` via `dependency/stream` and displays the data

^this above scenario is pretty straightforward.  

My question is, what if I want to add a dummy/pure UI screen `C` in between `A` and `B`.
so the new flow is like...
`A` presents `C`(only contains a button which navigates to `B`)
Obviously, `C` does not contain any business related logic. But how does `B` get data from `A`, do I need to create a RIB module for `C`?

**Comment by sbarow** [comment]
`C` would just be controlled in `A`'s view controller meaning `A` presents `C` and when the user clicks the button in `C` the call chain would be:

`C -> A (ViewController) -> A (Interactor) -> A (Router) present B`

**Comment by gogovan-terrypang** [comment]
thank so much for your quick reply.
> `C` would just be controlled in `A`'s view controller meaning `A` presents `C` and when the user clicks the button in `C` the call chain would be:
> 
> `C -> A (ViewController) -> A (Interactor) -> A (Router) present B`
but is that really possible?
I mean inside the interactor of `A`, I need to dismiss `C` first? before I present `B`?
or you meant there is a way for me to trigger the router inside A's interactor to do the job when the user clicked the button on `ViewController C` 🤔

**Comment by sbarow** [comment]
Well like you said C is just a pure UI component, so A Interactor doesn't need to know about it. It should be handled purely by A and A would communicate with the its Interactor.

**Comment by gogovan-terrypang** [comment]
sorry to bother you once more. 



> Well like you said C is just a pure UI component, so A Interactor doesn't need to know about it. It should be handled purely by A and A would communicate with its Interactor.

I understand if `C` is just a popup or modal view, then `A` interactor can easily handle it.
Let me clarify my original question(sorry maybe it was not clear),
what if `C` is a ViewController, not a view / simple UI component. 
`A interactor's router to C` and then where should I implement the routing logic from C to B 
to provide more details. 
assume
A B C are both view controllers
A modal presents C (which is wrapped in a UINavigationController), and when the user clicks a Button on C, the C's navigation controller needs to push to B
How will be the RIBs setup look like?
many thanks

**Comment by sbarow** [comment]
`C` should be a RIB in that case then.

**Comment by gogovan-terrypang** [comment]
> `C` should be a RIB in that case then.

that means I need to create a dedicate RIB for that non-business logic navigation and in order to pass the data stream down the RIB tree? 🤔 
and if the PM suddenly changes the requirements again(it happens), and we need to add two extra tutorial pages in between C & B. then we need two extra RIBs.
is that true 🤔 ?
(PS: I think after this one, we can close this issue. by the way, I think RIBs team should create a `RIBs architecture` tag on StackOverflow. thanks sooooo much)

**Comment by sbarow** [comment]
A view doesn't have to be seen as one RIB. `A` could be the parent of `C`, `D` & `E` (`D` & `E` being new screens your PM asked for), when I say parent I am specifically referring to c, d, e being child view controllers of a. 

So in your example `A` starts, it then displays its view, user clicks a button `A`'s ViewController lets the Interactor know it processes that piece of logic, the Interactor informs the Router that it should present the next tutorial page, the router can then call into its ViewController to then present the next tutorial page which in this case is just a plane view controller `C` or `D` or `E`.

Hope that makes sense?

**Comment by gogovan-terrypang** [comment]
> A view doesn't have to be seen as one RIB. `A` could be the parent of `C`, `D` & `E` (`D` & `E` being new screens your PM asked for), when I say parent I am specifically referring to c, d, e being child view controllers of a.
> 
> So in your example `A` starts, it then displays its view, user clicks a button `A`'s ViewController lets the Interactor know it processes that piece of logic, the Interactor informs the Router that it should present the next tutorial page, the router can then call into its ViewController to then present the next tutorial page which in this case is just a plane view controller `C` or `D` or `E`.
> 
> Hope that makes sense?

so can I interpret your suggestion as we may need to use Container View Controller (for iOS) or Fragment (for Android) to wrap them into one single RIB, correct? 🤔

**Comment by gogovan-terrypang** [comment]
thanks so much 👍

**Comment by ermik** [comment]
Please also see #269 #232 as well as #170.
