### ISSUE TITLE
Can I hook up a ViewController with multiple RIBs?

### ISSUE THREAD

**Issue by gogovan-terrypang** [uber/RIBs#299]
I am experimenting with all the possibilities of RIBs. And then I got stuck at a point. 
Seems like `Presentable` must be a `ViewControllerType` in iOS, that means I can not use `UIView` as a unit.
But how about I create a single `UIViewController` and I `extend` the ViewController with multiple RIBs 's `presentable`?

**Comment by ermik** [comment]
You can add as many subviews as you need to the ViewController; you can extend the delegate/listener pattern to have `UIView` talk back to the presenter if needed. But mainly i would suggest thinking about a single `UIViewController` as a terminus point for RIBs: the logic below the VC is beyond the scope of RIBs architecture.

The other concern here is that VC - View relationship is one with performance at stake, and coupling may be a good thing there.

NB: I think `ViewControllerType` may be anything, and `ViewControllable` must be a `UIViewController`.

**Comment by gogovan-terrypang** [comment]
got it thanks for your reply
