### ISSUE TITLE
Hi, how do i use RX to get a real time view of the Ribs hierachy tree

### ISSUE THREAD

**Issue by vrmmoreira** [uber/RIBs#300]
Hi,

i'm trying to on IOS get a real time log on the Ribs tree, how can i do this?

thanks,
Vitor

**Comment by artman** [comment]
You'd have to implement this yourself. The way we do it at Uber is to send events from each interactor's lifecycle to a manager that then can reconstruct the RIB tree based on create/remove messages it receives.
