### ISSUE TITLE
[Question] Mutate within RIB vs Attach/Detach state-specific RIB

### ISSUE THREAD

**Issue by chschen** [uber/RIBs#301]
Say Uber has the following business logic:
```
Side Menu
- Profile
- UberEats [exists in one country but not another]
Request
- Location refinement [exists in all countries but behavior and looks vary]
- Payment options [exists in all countries but exact options change, list can be provided by some service]
```

When mapping out the RIBs tree, it seems my options are either:
```
Root 
> Country A
    > Side Menu
        > Profile
    > Request
        > Country A Location refinement
        > Payment options
> Country B
    > Side Menu
        > Profile
        > UberEats
    > Request
        > Country B Location refinement
        > Payment options
> Country C
    ...
...
```
OR
```
Root 
> Side Menu (attached/detached UberEats based on location)
    > Profile
    > UberEats
> Request
    > Location refinement (switch cases inside to handle location variations)
    > Payment options
```

They both seem to have severe downsides: either a huge tree with lots of duplication, or RIBs with  huge switch cases inside. Is there one that makes more sense to adopt than the other? Or am I missing something and there's a better way to build this RIBs tree?

**Comment by artman** [comment]
The first option is pretty overkill as there's a lot of repetition (and you still have a switch case on the country that you're in). We use your second option everywhere and frankly it's never been a problem. It's in the nature of interactions to take in data and then make decisions on what children to attach, so attaching the UberEats based on some external condition is what interacts are there for.

**Comment by chschen** [comment]
Got it, option 1 definitely feels wrong given the sheer size from copy pasting.

As for not going straight with option 2, the main reservations were:
* having switch cases within a RIB where we know the number of cases will keep growing for sure (e.g. locations)
* seemingly mixing of rules: state of `UberEats` managed by attach/detach, state of `Location refinement` managed by itself

To combat the second point above, I've also considered:
```
Root 
> Side Menu (attached/detached UberEats based on location)
    > Profile
    > UberEats
> Request (attached/detached the right RIB based on location)
    > Country A Location refinement
    > Country B Location refinement
    > ...
    > Payment options
```

Is there a time when you guys take this option 3 approach or is it pretty consistently the mix and switch casing in option 2 above?

**Comment by artman** [comment]
Not sure if this applies to your case, but location refinement should most likely be moved to a parent interactor, or have a server made the decision for you. The menu should really just know what features are enabled, and not make the decision whether to enable one particular feature.

At Uber we've created a [plugin framework](https://eng.uber.com/plugins/) for this (and to tackle your first point of growing number of cases). The menu essentially just provides a place where plugins can attach labels onto. Whether a plugin is enabled is the responsibility of the plugin framework.

**Comment by gogovan-terrypang** [comment]
> Not sure if this applies to your case, but location refinement should most likely be moved to a parent interactor, or have a server made the decision for you. The menu should really just know what features are enabled, and not make the decision whether to enable one particular feature.
> 
> At Uber we've created a [plugin framework](https://eng.uber.com/plugins/) for this (and to tackle your first point of growing number of cases). The menu essentially just provides a place where plugins can attach labels onto. Whether a plugin is enabled is the responsibility of the plugin framework.

Concept wise, I understand. But is there a code example, how to implement the `Plugin Point`. Just a simply one would help a lot.
<img width="221" alt="screenshot 2018-11-29 at 3 54 25 pm" src="https://user-images.githubusercontent.com/44961031/49207160-1fbccb80-f3ef-11e8-933f-2cbc79c91685.png">
<img width="205" alt="screenshot 2018-11-29 at 3 54 31 pm" src="https://user-images.githubusercontent.com/44961031/49207161-1fbccb80-f3ef-11e8-93fd-4ccb79ef3402.png">

**Comment by chschen** [comment]
> The menu should really just know what features are enabled, and not make the decision whether to enable one particular feature.

At what point should one start using the plugin framework? It seems like you should use the plugin framework when many RIBs are parent to large numbers of children?
From what I understand the job of the plugin framework relates to what you said

**Comment by chschen** [comment]
I see, but what is the difference between deciding "switch on/off" with a plugin framework vs. with plain RIBs in the interactor like what @artman mentioned above?
> It's in the nature of interactions to take in data and then make decisions on what children to attach, so attaching the UberEats based on some external condition is what interacts are there for.

**Comment by sbarow** [comment]
> I see, but what is the difference between deciding "switch on/off" with a plugin framework vs. with plain RIBs in the interactor like what @artman mentioned above?

The way that our plugins work is they check for applicability, if a RIB is applicable then it will be built, if not then nothing happens. With the mentioned approach of using `attach/detach` you would need to build the RIB's first and then activate them.
