### ISSUE TITLE
[Question] About dagger usage in Kotlin

### ISSUE THREAD

**Issue by gogovan-terrypang** [uber/RIBs#307]
Hey there, our team is developing our new app using RIBs and Kotlin. We had played around with the java tutorial project. So first we tried to rewrite the java tutorial project in Kotlin but seems like the dagger part does not work as we expected. 

Referring to tutorial 3
https://github.com/uber/RIBs/wiki/Android-Tutorial-3

We tried to DI the `player_one` and `player_two` from `LoggedIn` to `OffGame`. But ends up in the `OffGameInteractor`, we can not get back the values.
Are the annotations correctly used? 
Cause we found that the annotations are used differently across Java and Kotlin. 
Any help is appreciated.

```
@BindsInstance
fun playerOne(@Named("player_one") playerOne: String): Builder

@BindsInstance
fun playerTwo(@Named("player_two") playerTwo: String): Builder
```

```
public interface ParentComponent {
  @Named("player_one") fun playerOne(): String
  @Named("player_two") fun playerTwo(): String
}
```

```
In OffGameInteractor:

@set:[Inject Named("player_one")] var playerOne: String = null
@set:[Inject Named("player_two")] var playerTwo: String = null
```

**Comment by melbystyle** [comment]
try
``` kotlin
@Inject
@field:Named("player_one") lateinit var playerOne: String
```

**Comment by gogovan-terrypang** [comment]
thanks @melbystyle  the team said it works
