### ISSUE TITLE
[Bug] [iOS] Swift 5

### ISSUE THREAD

**Issue by RubenEsposito** [uber/RIBs#317]
Error when compiling under Swift 5, Xcode 10.2. Fixed by changing `open let dependency: DependencyType` to `public let dependency: DependencyType` in file `Component.swift`

**Comment by sbarow** [comment]
Should be fixed with #316

**Comment by sbarow** [comment]
@RubenEsposito should be fixed on latest master.

**Comment by kor45cw** [comment]
@sbarow 0.9.3 and xcode 10.2 
The issue seems to occur despite the current version

**Comment by ZeGerm4n** [comment]
I have this issue with Xcode 12.3 and RIBs v0.9.1
