### ISSUE TITLE
UI Input validation : Presenter or Interactor ?

### ISSUE THREAD

**Issue by 5torm5h4dow** [uber/RIBs#335]
Where would be the right place to put the validation code for the user input ,for eg : validation of address, name etc.. . Would this demand the use of the presenter or do we put the validation code in the Interactor itself? If I remember correctly, clean architecture mentions somewhere it's best not to have the input validation in the Interactor.

**Comment by alexvbush** [comment]
put it in presenter or viewmodel, interactor is for business logic.

**Comment by 5torm5h4dow** [comment]
> put it in presenter or viewmodel, interactor is for business logic.

Wanted to confirm.Thanks
