### ISSUE TITLE
Please reach out to your Uber Business Development representative for server token access.

### ISSUE THREAD

**Issue by charliekayaker** [uber/RIBs#341]
Hi everybody!

I have a problem when i try get server token. 

The page say me:

"Please reach out to your Uber Business Development representative for server token access."

Anybody can i help me?

Thanks in advance.!

**Comment by igor-shyrnin** [comment]
me 2. Already 2 months without uber API (request /estimate/price)

**Comment by vslala** [comment]
any update? I'm also getting the same message.

**Comment by sbarow** [comment]
Can you add more context here? When are you running into this issue?

**Comment by winac** [comment]
@sbarow Having the same issue. I have created an app in the uber developer dashboard so that I could access uber's API however accessing the API requires a Server Token. When going back into the app to find the server token I see the image linked https://postimg.cc/bZQscYNv

**Comment by sbarow** [comment]
This isn't related to RIBs. Possibly look at posting here https://github.com/uber/rides-ios-sdk/issues

**Comment by chachramohit** [comment]
I am also getting the same problem
if you have the solution then please let me know

**Comment by chachramohit** [comment]
You can go ahead without adding Server Token your app will work properly.
In the past, I also faced this problem but without adding server token my app started working properly.

**Comment by Eddy-Morgan** [comment]
session = Session()
client = UberRidesClient(session)

Like this?

**Comment by rjyoung** [comment]
> You can go ahead without adding Server Token your app will work properly.
> In the past, I also faced this problem but without adding server token my app started working properly.

Can you please give a code example of how you managed to do this? I am working on a school project that requires the use of the Uber api and my group is having trouble with obtaining a Session() and Uber seems to be restricting access to server tokens and scope info.

**Comment by chachramohit** [comment]
I have not used any server token I have kept this column as blank.


My code for the uber ride button is attached below


`SessionConfiguration config = new SessionConfiguration.Builder().
                setClientId("lKkYsil2aLxytykLD18DE0MJDYpY63CT").
                setServerToken("").
                //setRedirectUri().
                setScopes(Arrays.asList(Scope.RIDE_WIDGETS)).
                setEnvironment(SessionConfiguration.Environment.PRODUCTION).
                build();

        UberSdk.initialize(config);
        RideRequestButton requestButton = new RideRequestButton(MainActivity.this);
        RelativeLayout layout = new RelativeLayout(this);
        layout.addView(requestButton);

        RideParameters rideParams = new RideParameters.Builder()
                // Optional product_id from /v1/products endpoint (e.g. UberX). If not provided, most cost-efficient product will be used
                .setProductId("a1111c8c-c720-46c3-8534-2fcdd730040d")
                // Required for price estimates; lat (Double), lng (Double), nickname (String), formatted address (String) of dropoff location
                .setDropoffLocation(
                        37.775304, -122.417522, "Uber HQ", "1455 Market Street, San Francisco")
                // Required for pickup estimates; lat (Double), lng (Double), nickname (String), formatted address (String) of pickup location
                .setPickupLocation(37.775304, -122.417522, "Uber HQ", "1455 Market Street, San Francisco")
                .build();
// set parameters for the RideRequestButton instance
        ServerTokenSession session = new ServerTokenSession(config);
        requestButton.setSession(session);
        requestButton.setRideParameters(rideParams);

        requestButton.loadRideInformation();`

**Comment by chachramohit** [comment]
I have not used any server token I have kept this column as blank.

My code for the uber ride button is attached below





SessionConfiguration config = new SessionConfiguration.Builder().
                setClientId("lKkYsil2aLxytykLD18DE0MJDYpY63CT").
                setServerToken("").
                //setRedirectUri().
                setScopes(Arrays.asList(Scope.RIDE_WIDGETS)).
                setEnvironment(SessionConfiguration.Environment.PRODUCTION).
                build();

        UberSdk.initialize(config);
        RideRequestButton requestButton = new RideRequestButton(MainActivity.this);
        RelativeLayout layout = new RelativeLayout(this);
        layout.addView(requestButton);

        RideParameters rideParams = new RideParameters.Builder()
                // Optional product_id from /v1/products endpoint (e.g. UberX). If not provided, most cost-efficient product will be used
                .setProductId("a1111c8c-c720-46c3-8534-2fcdd730040d")
                // Required for price estimates; lat (Double), lng (Double), nickname (String), formatted address (String) of dropoff location
                .setDropoffLocation(
                        37.775304, -122.417522, "Uber HQ", "1455 Market Street, San Francisco")
                // Required for pickup estimates; lat (Double), lng (Double), nickname (String), formatted address (String) of pickup location
                .setPickupLocation(37.775304, -122.417522, "Uber HQ", "1455 Market Street, San Francisco")
                .build();
// set parameters for the RideRequestButton instance
        ServerTokenSession session = new ServerTokenSession(config);
        requestButton.setSession(session);
        requestButton.setRideParameters(rideParams);

        requestButton.loadRideInformation();

**Comment by travis-st** [comment]
Looks like Uber doesn't really care about supporting developers.

Twitter @UberDevelopers hasn't been updated in 2 years
The "Blog" hasn't been updated since 2018
The Google Groups for "Support" does not exist

Awesome!

**Comment by TonySlon** [comment]
I have the same problem and don't know what to do....

**Comment by travis-st** [comment]
Go with postmates instead, we have been happy with them.

https://postmates.com/developer

**Comment by vipu-sa** [comment]
> You can go ahead without adding Server Token your app will work properly.
> In the past, I also faced this problem but without adding server token my app started working properly.

Have you used this uber code with React-Native app?

**Comment by MohitChachra** [comment]
> > You can go ahead without adding Server Token your app will work properly.
> > In the past, I also faced this problem but without adding server token my app started working properly.
> 
> Have you used this uber code with React-Native app?

No, I just used the uber code with Android App.
