### ISSUE TITLE
[iOS] after Swift5 Component Dependecy not compiled just warning

### ISSUE THREAD

**Issue by kor45cw** [uber/RIBs#342]
```
'let' properties are implicitly 'final'; use 'public' instead of 'open'
```
<img width="822" alt="스크린샷 2019-08-08 오전 10 30 29" src="https://user-images.githubusercontent.com/4055267/62668640-8c995400-b9c7-11e9-9ec3-f338c4883d04.png">

I modified it according to the suggested one, but there seems to be a problem with passing the component.

<img width="824" alt="스크린샷 2019-08-08 오전 10 32 40" src="https://user-images.githubusercontent.com/4055267/62668721-dd10b180-b9c7-11e9-9b9a-b360d7f5c98f.png">

<img width="795" alt="스크린샷 2019-08-08 오전 10 33 02" src="https://user-images.githubusercontent.com/4055267/62668735-e7cb4680-b9c7-11e9-9279-fbf9b6123a8b.png">

<img width="676" alt="스크린샷 2019-08-08 오전 10 33 40" src="https://user-images.githubusercontent.com/4055267/62668754-ffa2ca80-b9c7-11e9-8ebe-79777e18d475.png">

I do not know how to solve this. Please check.

**Comment by kor45cw** [comment]
PodSpec has been updated to 0.9.3. However, the new version is not released. We hope to release version 0.9.3 soon.

**Comment by jafara** [comment]
@kor45cw make sure to fix https://github.com/uber/RIBs/issues/337 for next release
