### ISSUE TITLE
No such module "RIBs"

### ISSUE THREAD

**Issue by lukepighetti** [uber/RIBs#344]
I'm on `cocoapods` v1.7.5. I navigate to `ios/tutorials/tutorial1` and type `pod install`. After selecting a Team in xCode, I go to build, and I get an error

`No such module 'RIBs'` on line 17 of `AppDelegate.swift`

Is this related to an issue with `uber/RIBs`?

**Comment by lukepighetti** [comment]
Have to open `TicTacToe.xcworkspace` instead of `TicTacToe.xcodeproj`

**Comment by PradeepMithna** [comment]
im also facing same issue any solution for that
