### ISSUE TITLE
Using an open-source version of Combine instead of RxSwift

### ISSUE THREAD

**Issue by michaeleisel** [uber/RIBs#346]
Because RxSwift and Combine are so similar, and because Combine is an Apple-provided library, would it be worth it to switch to a backwards-compatible version of it, e.g. [OpenCombine](https://github.com/broadwaylamb/OpenCombine)? That project says that it's in "early development", and I don't know of any other version of Combine, but perhaps it would be worth thinking about right now.

**Comment by rudro** [comment]
In hindsight, we can now see that Apple may deprecate Combine in favor of AsyncStream and it's related operators. Guess it was a good call not to move to OpenCombine after all.
