### ISSUE TITLE
Best approach for nested routers

### ISSUE THREAD

**Issue by tezqa** [uber/RIBs#355]
Hi!

Suppose we have this hierarchy:

`NewsRIB (Headless) -> NewsListRIB -> NewsDetailsRIB -> NewsCommentsRIB`

We need to push the `NewsDetailsRIB` from the `NewsListRIB` and the `NewsCommentsRIB` from the `NewsDetailsRIB`.

What is the right approach about the routers?

A. Each RIB's routers are responsible to implement methods to push their related RIB. 
e.g. : the `NewsListRIB` router should implement an `attachNewsDetailsRIB()` method.

B. The headless `NewsRIB` should implement all methods, triggered by its interactor listening to events from other RIBS

**Comment by rudro** [comment]
(Yes, I know it's been 3 years!)

Both answers are fine. In the case of a navigation controller (iOS) case, often people will have the first RIB -- the headless one in your example -- own the nav controller and push the screens as needed. This is especially useful when the flow can change (perhaps the server gets to send down the sequence of screens). Even without the dynamic thing, some people still prefer this model.

If the screens present each other, say as full screen views, then people seem to prefer option A.

We have plenty of examples of both patterns in our codebase.
