### ISSUE TITLE
[Android] RIBs Roadmap

### ISSUE THREAD

**Issue by jbarr21** [uber/RIBs#390]
The Android portion of this project will be undergoing two groups of breaking changes as we look at the future of RIBs.
1. Breaking changes required in order to reconcile the differences with our internal version of RIBs (#392)
    - programmatic changes
    - artifact renames
    - minimal behavioral changes
2. Convert the library to Kotlin (#412)
    - keep the same API
3. Breaking changes required in order to add support for:
    - Better Kotlin support
    - Declarative UIs
    - ViewModels

**Comment by andreasnomikos** [comment]
Why not iOS too? Are we going to just prototype Android first and adapt iOS later or is there a fundamental difference in the platforms that warrants a divergence in architecture?

**Comment by Solace-Studios** [comment]
@jbarr21 @tyvsmith Is this still the roadmap?

**Comment by tyvsmith** [comment]
The set of work items called out here, the Kotlinificaiton of Ribs, Compose support, and Coroutines support have been finished, and we're now in a maintenance cycle. I'm going to close this ticket out, and as we define new Roadmap items, they'll be created as new issues.
