### ISSUE TITLE
Convert RIBs to Kotlin

### ISSUE THREAD

**Issue by jbarr21** [uber/RIBs#412]
Perform a straight convert to Kotlin without API changes before making improvements

**Comment by ShaishavGandhi** [comment]
We can integrate with [japicmp](https://github.com/melix/japicmp-gradle-plugin) to make sure we're API compatible

**Comment by jbarr21** [comment]
> We can integrate with [japicmp](https://github.com/melix/japicmp-gradle-plugin) to make sure we're API compatible

Good suggestion! #416
