### ISSUE TITLE
LeakCanary 2 integration

### ISSUE THREAD

**Issue by ericntd** [uber/RIBs#423]
Hi there, as soon as I installed
```
kapt 'com.uber.rib:rib-compiler-test:0.10.1'
    implementation 'com.uber.rib:rib-android:0.10.1'
    debugImplementation 'com.uber.rib:rib-android:0.10.1'
```

LeakCanary imports became unresolved
<img width="646" alt="Screen Shot 2021-03-31 at 2 55 07 PM" src="https://user-images.githubusercontent.com/19919208/113196111-1e0aa900-9231-11eb-8886-2a30db6b9874.png">

Same issue didn't happened for LeakCanary 1.6.3

**Comment by jbarr21** [comment]
RIBs doesn't have a direct dependency on LeakCanary, so you can use whichever version that you choose. LeakCanary v2 has breaking changes that require updates to your codebase (public APIs are now in `leakcanary.*`. you can read more on their[ Upgrade Page](https://square.github.io/leakcanary/upgrading-to-leakcanary-2.0/)
