### ISSUE TITLE
LeakCanary 1.6.3 showing blank

### ISSUE THREAD

**Issue by ericntd** [uber/RIBs#424]
![113198184-9ecaa480-9233-11eb-81ec-93c8142117be](https://user-images.githubusercontent.com/19919208/113717610-c8fbe680-96b9-11eb-927c-62d6a12e27a7.png)

```java
public class DebugApplication extends MyApplication {
  @SuppressLint("MParticleInitialization")
  @Override
  public void onCreate() {
    super.onCreate();

    final RefWatcher refWatcher = LeakCanary
            .refWatcher(this)
            .watchDelay(2, TimeUnit.SECONDS)
            .buildAndInstall();
    RibRefWatcher.getInstance().setReferenceWatcher(new RibRefWatcher.ReferenceWatcher() {
      @Override
      public void watch(Object object) {
        refWatcher.watch(object);
      }

      @Override
      public void logBreadcrumb(String eventType, String data, String parent) {
        // Ignore for now. Useful for collecting production analytics.
      }
    });
  }

  @Override
  protected void setupFirebase() {
    FirebaseApp.initializeApp(this);
  }
}
```

Versions:
```
"com.squareup.leakcanary:leakcanary-android:1.6.3",
"com.squareup.leakcanary:leakcanary-android-no-op:1.6.3",
kapt 'com.uber.rib:rib-compiler-test:0.10.1'
    implementation 'com.uber.rib:rib-android:0.10.1'
    debugImplementation 'com.uber.rib:rib-android:0.10.1'
```

**Comment by jbarr21** [comment]
@ericntd it looks like you may be missing the [enabling of the RibRefWatcher](https://github.com/uber/RIBs/blob/master/android/demos/memory-leaks/src/main/java/com/uber/rib/SampleApplication.java#L54) at the end of your `onCreate()`

i just double checked and LeakCanary 1.x found the sample leak in our [Sample Project](https://github.com/uber/RIBs/blob/master/android/demos/memory-leaks/README.md). if that works for you then please let me know and i'll be sure to update our README for that project
