### ISSUE TITLE
Recreate RIBs to ModernRIBs

### ISSUE THREAD

**Issue by DevYeom** [uber/RIBs#452]
[ModernRIBs](https://github.com/DevYeom/ModernRIBs) is recreated by removing additional dependencies such as RxSwift from RIBs. If you have any problems with redistribution or licensing, please let me know and i will take action immediately.

p.s. May I ask you a code review for this project? 👀

**Comment by rudro** [comment]
No problems.

I took a quick glance, and it seems fine. We don't use Combine at Uber, so if there are some subtle mistakes with your Publishers, I will unfortunately have missed them. Given that our usage of RxSwift in RIBs is quite basic, hopefully you have no issues with your fork.

**Comment by programming086** [comment]
@rudro Don't we use this RIBs at Uber on iOS too?
