### ISSUE TITLE
Who is in charge for the iOS side ?

### ISSUE THREAD

**Issue by juliengdt** [uber/RIBs#496]
Brief question, need a brief answer 😊

I saw (too) many opened issues regarding the iOS framework, I was wondering who is/are responsible of it. (not obvious when I look at the contributors and people who reply on iOS-specific issues)

Thank you !

Cheers everyone 👋

**Comment by Solace-Studios** [comment]
@tyvsmith do you have an answer?

**Comment by rudro** [comment]
Hi,

For the time being, I'll be in charge of the iOS side of the framework.

Thanks,
Rudro.

**Comment by alexvbush** [comment]
@rudro thank you for leading on this! RIBs is Uber's project and you guys probably want to have control over implementation of it and align it with internal usage of RIBs but if you ever need help from open source community I'd be happy to help on the iOS side.

**Comment by programming086** [comment]
@tyvsmith do you have an answer?
