### ISSUE TITLE
Ribs Intellij/ Android studio Code generation Plugin not working

### ISSUE THREAD

**Issue by er-abhishek-luthra** [uber/RIBs#515]
As mentioned in step [here](https://github.com/uber/RIBs/wiki/Android-Tooling#plugin-installation-instructions), The [RIBs Code Generation Plugin](https://github.com/uber/RIBs/wiki/Android-Tooling#ribs-code-generation-plugin-for-android-studio-and-intellij) does get installed but doesnot  work on Android Studio Chipmunk and later. No New Rib option is visible in **New** menu.

**Comment by Mike-the-Monsta** [comment]
I tried to build the plugin locally and install it and I get this on Android Studio Chipmunk 
![image](https://user-images.githubusercontent.com/24611770/181364004-2a1c8598-19f1-415e-93fd-2286fc316302.png)

**Comment by Mike-the-Monsta** [comment]
I'm not sure why it wouldn't be able to find that class, it's right there 
![image](https://user-images.githubusercontent.com/24611770/181364869-e7660d99-1c11-43b8-9acd-0331fdbe6aed.png)

**Comment by Mike-the-Monsta** [comment]
Current workaround is for Android Studio to be installed at the latest version of bumblebee 
Android Studio Bumblebee (2021.1.1) Patch 3 April 7, 2022
https://developer.android.com/studio/archive
