### ISSUE TITLE
[Android][Screenstack] Missing open modifier in ViewProvider.kt

### ISSUE THREAD

**Issue by Malkkit** [uber/RIBs#516]
Hi.

The method doOnViewRemoved can not be implemented because it is final without the open modifier.

Actual code
`
  /**
   * Callers can implement this in order to complete additional work when a call to [ ][.onViewRemoved] is performed.
   */
  protected fun doOnViewRemoved() {}
`

**Comment by tyvsmith** [comment]
Resolved in #518
