### ISSUE TITLE
Update Android repo to Kotlin 1.7.10

### ISSUE THREAD

**Issue by tyvsmith** [uber/RIBs#521]
Update Kotlin to 1.7.10 and all associated deps.

**Comment by SharmaDhruv2511** [comment]
@tyvsmith I want to ask that To convert the Android Repo to Kotlin Do I have to code again or just convert the file to Kotlin???

**Comment by tyvsmith** [comment]
This was closed in https://github.com/uber/RIBs/pull/525. @SharmaDhruv2511

I renamed your existing PR to more accurately capture your workstream converting remaining java to kt.
