### ISSUE TITLE
Add support for RxJava3, since RxJava2 is End of Life

### ISSUE THREAD

**Issue by franklinharper** [uber/RIBs#529]
Quoting from https://github.com/ReactiveX/RxJava/blob/3.x/README.md#version-2x

> Version 2.x
> The [2.x version](https://github.com/ReactiveX/RxJava/tree/2.x) is end-of-life as of February 28, 2021. No further
> development, support, maintenance, PRs and updates will happen. The Javadoc of the very last version, 2.2.21, will remain accessible.

Are plans to migrate to RxJava3? Or has the decision been made to stick with RxJava2?

**Comment by tyvsmith** [comment]
We will not be migrating to Rxjava3. We do plan to remove Rx entirely in favor of coroutines/Flow, but that is not high priority right now.

**Comment by Solace-Studios** [comment]
@tyvsmith wouldn't that mean iOS and Android would lose code sharing of business logic? Does swift have coroutines/Flow?

**Comment by tyvsmith** [comment]
Android and iOS do not share code, only high-level design patterns for core architecture pieces.

iOS has no plans to drop RxSwift for now, but may look into Apple official async apis in the future.
