### ISSUE TITLE
Broken Link In The Documentation Section

### ISSUE THREAD

**Issue by crjacinro** [uber/RIBs#598]
Broken Link : https://eng.uber.com/new-rider-app

> To read about the backstory on why we created RIBs, see [this blog post](https://eng.uber.com/new-rider-app/) we wrote when releasing RIBs in production the first time and see this short video where we discussed how the RIBs architecture works.

**Comment by FranAguilera** [comment]
Thanks for reporting. Updating link here https://github.com/uber/RIBs/pull/600
