### ISSUE TITLE
Move iOS Ribs to separate repo

### ISSUE THREAD

**Issue by tyvsmith** [uber/RIBs#640]
Due to the difference in support level between Android and iOS RIBS, the plan is to move iOS to a github.com/uber/ribs-ios repo, and repurpose this repo exclusively for Android, which will remain actively maintained. 

The iOS repo will look for alternative internal maintainers at Uber to sync the internal differences with the external repo and continue maintenance, otherwise will be considered for external maintainership or archival.

**Comment by rbrovko** [comment]
@tyvsmith  They promised to move it in September. The month is already over and no work is visible. When will it be done?
