### ISSUE TITLE
Release to maven central

### ISSUE THREAD

**Issue by AttwellBrian** [uber/RIBs#83]
Spent a couple hours trying to get this work without success. To meet our deadlines I think someone that already has their keys setup should do this.

Ie, @hzsweers

**Comment by msridhar** [comment]
I uploaded the artifacts but did not promote them.  @AttwellBrian you can close whenever appropriate

**Comment by hzsweers** [comment]
If brian doesn't have perms set up yet, one of us (@msridhar or me) will need to finish the release too

**Comment by msridhar** [comment]
I don't see the repo in the list of staging repositories on Sonatype.  Maybe I don't have the right permissions to see it?

**Comment by AttwellBrian** [comment]
I have the com.uber permission for sonatype. But I don't see Manu's entry here.

**Comment by msridhar** [comment]
That's weird.  I ran `./gradlew clean uploadArchives` and it succeeded.  Maybe it just failed silently?

**Comment by AttwellBrian** [comment]
Got it working.

The internal wiki used the wrong field names for sonatype password and username.
